function [position, orientation] = ParseRosOdometry(odomMsg)
    position = [odomMsg.Pose.Pose.Position.X, odomMsg.Pose.Pose.Position.Y, odomMsg.Pose.Pose.Position.Z];
    orientation = [odomMsg.Pose.Pose.Orientation.W, ...
                    odomMsg.Pose.Pose.Orientation.X, ...
                    odomMsg.Pose.Pose.Orientation.Y, ...
                    odomMsg.Pose.Pose.Orientation.Z];
end