function yamlStr = writeCalibrationToYamlFile(intrinsics, extrinsics)
% WRITECALIBRATIONTOYAMLFILE  Takes intrinsics and extrinsics and writes to
% YAML file. Uses createYANMLstringROS to format the YAML file.
% Format compatible with default camera info ROS format. 
% See https://wiki.ros.org/camera_calibration_parsers#File_formats
% Also writing camera-lidar transformation to file (non-standard).
    yamlStr = createYAMLstringROS(intrinsics, extrinsics);

    % Get the current date and time
    currentTime = datetime('now', 'Format', 'yyyy-MM-dd-HH-mm-ss');
    
    % Create new file name
    newFileName = sprintf('%s-camera-info-matlab.yaml', currentTime);
    
    % Write YAML string to file
    fid = fopen(newFileName, 'w');
    if fid == -1
        error('Cannot open file for writing: %s', newFileName);
    end
    fprintf(fid, '%s', yamlStr);
    fclose(fid);

    fprintf('YAML output has been written to %s\n', newFileName);
end

function yamlStr = createYAMLstringROS(intrinsics, extrinsics)
% WRITECALIBRATIONTOYAMLFILE  Takes intrinsics and extrinsics and creates a
% YAML formatted string. Format compatible with default ROS format. 
% See https://wiki.ros.org/camera_calibration_parsers#File_formats
    
    % Create YAML-formatted text string from intrinsics and extrinsics structs
    camera_matrix_str = sprintf('%.15g, %.15g, %.15g, %.15g, %.15g, %.15g, %.15g, %.15g, %.15g', ...
            intrinsics.FocalLength(1), 0, intrinsics.PrincipalPoint(1), ...
            0, intrinsics.FocalLength(2), intrinsics.PrincipalPoint(2), ...
            0, 0, 1);
    
    distortion_coeffs_str = sprintf('%.15g, %.15g, %.15g, %.15g, %.15g', ...
        intrinsics.RadialDistortion(1), intrinsics.RadialDistortion(2), ...
        intrinsics.TangentialDistortion(1), intrinsics.TangentialDistortion(2), 0);

    projection_matrix_str = sprintf('%.15g, %.15g, %.15g, %.15g, %.15g, %.15g, %.15g, %.15g, %.15g, %.15g, %.15g, %.15g', ...
            intrinsics.FocalLength(1), 0, intrinsics.PrincipalPoint(1), 0, ...
            0, intrinsics.FocalLength(2), intrinsics.PrincipalPoint(2), 0, ...
            0, 0, 1, 0);

    % Transformation Matrix (T_lidar_cam)
    T_lidar_cam = sprintf('%.15g, %.15g, %.15g, %.15g, %.15g, %.15g, %.15g, %.15g, %.15g, %.15g, %.15g, %.15g, %.15g, %.15g, %.15g, %.15g', ...
            extrinsics.T_lidar_cam(1,1), extrinsics.T_lidar_cam(1,2), extrinsics.T_lidar_cam(1,3), extrinsics.T_lidar_cam(1,4), ...
            extrinsics.T_lidar_cam(2,1), extrinsics.T_lidar_cam(2,2), extrinsics.T_lidar_cam(2,3), extrinsics.T_lidar_cam(2,4), ...
            extrinsics.T_lidar_cam(3,1), extrinsics.T_lidar_cam(3,2), extrinsics.T_lidar_cam(3,3), extrinsics.T_lidar_cam(3,4), ...
            extrinsics.T_lidar_cam(4,1), extrinsics.T_lidar_cam(4,2), extrinsics.T_lidar_cam(4,3), extrinsics.T_lidar_cam(4,4));

    % Construct YAML string
    yamlStr = sprintf(['image_width: %d\n' ...
        'image_height: %d\n' ...
        'camera_name: %s\n' ...
        'camera_matrix:\n' ...
        '  rows: 3\n' ...
        '  cols: 3\n' ...
        '  data: [%s]\n' ...
        'distortion_model: plumb_bob\n' ...
        'distortion_coefficients:\n' ...
        '  rows: 1\n' ...
        '  cols: 5\n' ...
        '  data: [%s]\n' ...
        'rectification_matrix:\n' ...
        '  rows: 3\n' ...
        '  cols: 3\n' ...
        '  data: [1, 0, 0, 0, 1, 0, 0, 0, 1]\n' ...
        'projection_matrix:\n' ...
        '  rows: 3\n' ...
        '  cols: 4\n' ...
        '  data: [%s]\n' ...
        'transformation_lidar_cam_matrix:\n' ...
        '  rows: 4\n' ...
        '  cols: 4\n' ...
        '  data: [%s]\n'], ...
        intrinsics.ImageSize(2), intrinsics.ImageSize(1), 'FLIR Oryx', ...
        camera_matrix_str, ...
        distortion_coeffs_str, ...
        projection_matrix_str, ...
        T_lidar_cam);
end

function yamlStr = createYAMLstringKalibr(intrinsics, extrinsics)
    % Create YAML-formatted text string from intrinsics and extrinsics structs

    % Intrinsics
    intrinsics_combined = sprintf('[%.15g, %.15g, %.15g, %.15g]', ...
        intrinsics.FocalLength(1), intrinsics.FocalLength(2), ...
        intrinsics.PrincipalPoint(1), intrinsics.PrincipalPoint(2));
    
    % Distortion Coefficients
    distortion_coeffs = [intrinsics.RadialDistortion, intrinsics.TangentialDistortion];

    distortion_coeffs_str = sprintf('[%.15g, %.15g, %.15g, %.15g]', ...
        distortion_coeffs(1), distortion_coeffs(2), ...
        distortion_coeffs(3), distortion_coeffs(4));

    % Image Size (Resolution)
    resolution = sprintf('[%d, %d]', intrinsics.ImageSize(2), intrinsics.ImageSize(1));

    % Transformation Matrix (T_lidar_cam)
    T_lidar_cam = sprintf('- [%.15g, %.15g, %.15g, %.15g]\n  - [%.15g, %.15g, %.15g, %.15g]\n  - [%.15g, %.15g, %.15g, %.15g]\n  - [%.15g, %.15g, %.15g, %.15g]', ...
        extrinsics.T_lidar_cam(1,1), extrinsics.T_lidar_cam(1,2), extrinsics.T_lidar_cam(1,3), extrinsics.T_lidar_cam(1,4), ...
        extrinsics.T_lidar_cam(2,1), extrinsics.T_lidar_cam(2,2), extrinsics.T_lidar_cam(2,3), extrinsics.T_lidar_cam(2,4), ...
        extrinsics.T_lidar_cam(3,1), extrinsics.T_lidar_cam(3,2), extrinsics.T_lidar_cam(3,3), extrinsics.T_lidar_cam(3,4), ...
        extrinsics.T_lidar_cam(4,1), extrinsics.T_lidar_cam(4,2), extrinsics.T_lidar_cam(4,3), extrinsics.T_lidar_cam(4,4));

    % Construct YAML string
    yamlStr = sprintf(['cam0:\n' ...
        '  camera_model: pinhole\n' ...
        '  intrinsics: %s\n' ...
        '  distortion_model: plumb_bob\n' ...
        '  distortion_coeffs: %s\n' ...
        '  resolution: %s\n' ...
        '  T_lidar_cam:\n' ...
        '  %s\n'], ...
        intrinsics_combined, distortion_coeffs_str, resolution, T_lidar_cam);
end




