#!/usr/bin/env python3

"""Helpers for writing generated files without disturbing the build graph."""

import os


def write_if_changed(path, text):
    """Write <text> to <path> only when it differs from what is already there.

    Every generated parameter header is an input to the C++ compile step, so
    rewriting one with identical content still updates its mtime and forces
    every translation unit that includes it to recompile. That matters because
    the headers for a package are generated by a single batched command: a
    change to one template yaml re-runs the generator for all of them, and
    without this guard a one-line edit would rebuild the whole package.

    Returns True if the file was actually written.
    """
    if os.path.isfile(path):
        try:
            with open(path, encoding='utf-8') as handle:
                if handle.read() == text:
                    return False
        except (OSError, UnicodeDecodeError):
            # Unreadable or not valid utf-8: fall through and overwrite it.
            pass

    output_dir = os.path.dirname(path)
    if output_dir and not os.path.isdir(output_dir):
        os.makedirs(output_dir)

    with open(path, 'w', encoding='utf-8') as handle:
        handle.write(text)
    return True
