function [terrainSubGrid, terrainSubgridSize, terrainModifiedCellIdxs, ...
    obstacleSubGrid, obstacleSubgridSize, obstacleModifiedCellIdxs] = perception_wrapper(img,...
        pc,...
        odom,...
        cameraInfo,...
        cameraToLidarTform,...
        lidarToVboxTform,...
        invertLidarZRot, ...
        convertNEDToENU, ...
        correctColor, ...
        grid_width,grid_height,cell_size,grid_llx,grid_lly)
rosPc = BuildRosPointCloud2Msg(pc.width, pc.height, pc.point_step, pc.row_step, pc.data);
rosImg = BuildRosImageMsg(img.width, img.height, img.encoding, img.data, img.step);
odomMsg = BuildRosOdometryMsg(odom.translation.x, ...
                            odom.translation.y, ...
                            odom.translation.z, ...
                            odom.orientation.w, ...
                            odom.orientation.x, ...
                            odom.orientation.y, ...
                            odom.orientation.z);

defaultTerrainCellVal = 0.6;
defaultObstacleCellVal = 0.5;
%% Initialize Occupancy Grid
persistent gridBuilder
if isempty(gridBuilder)
    grid_res = cell_size;
    % confidence values
    lowConfidenceVal = 0.3;
    highConfidenceVal = 0.7;
    
    % trafficability costs (pretty arbitrary)
    lowTraffCost = 50;
    mediumTraffCost = 33;
    highTraffCost = 1;
    
    gridBuilder = GridBuilder(grid_width, ...
                                grid_height, ...
                                grid_res, ...
                                grid_llx, ...
                                grid_lly, ...
                                defaultTerrainCellVal, ...
                                defaultObstacleCellVal, ...
                                highConfidenceVal, ...
                                lowConfidenceVal, ...
                                highTraffCost, ...
                                mediumTraffCost, ...
                                lowTraffCost);
end

gridBuilder.GridOffsetX = grid_llx;
gridBuilder.GridOffsetY = grid_lly;

persistent segmentationModel
if isempty(segmentationModel)
    % todo: select models from ROS node
    modelParams = 'sae_net_5class_RUGD_GOD_544_688_package.mat';
    
    % AECESN (trained on MSU virtual data)
    % modelParams = 'ae_net_REL_RUG_VS_MSUVS.mat';
    segmentationModel = CAE(modelParams);
end

persistent lidarProcessingModel
if isempty(lidarProcessingModel)
    pcPostProcessingEnabled = true;
    lidarProcessingModel = KNN(pcPostProcessingEnabled);
end

% build lidar to camera transform from ROS2 TransformStamped message
rot = quaternion(cameraToLidarTform.rotation.w,...
                    cameraToLidarTform.rotation.x,...
                    cameraToLidarTform.rotation.y,...
                    cameraToLidarTform.rotation.z);
translation = [cameraToLidarTform.translation.x, cameraToLidarTform.translation.y, cameraToLidarTform.translation.z];
cameraToLidarTransform = rigidtform3d(quat2rotm(rot), translation);

% build lidar to vbox transformation from ROS2 TransformStamped message
lidarToVboxTransformation = eye(4);
lidarVboxRot = quaternion(lidarToVboxTform.rotation.w,...
                            lidarToVboxTform.rotation.x,...
                            lidarToVboxTform.rotation.y,...
                            lidarToVboxTform.rotation.z);
lidarToVboxTransformation(1:3, 1:3) = quat2rotm(lidarVboxRot);
lidarVboxTranslation = [lidarToVboxTform.translation.x, lidarToVboxTform.translation.y, lidarToVboxTform.translation.z];
lidarToVboxTransformation(1:3, 4) = lidarVboxTranslation;

[terrainSubGrid,terrainSubgridSize,terrainModifiedCellIdxs, ...
    obstacleSubGrid,obstacleSubgridSize,obstacleModifiedCellIdxs,...
    camera,segmentedCam,lidar,segmentedPC] = main(rosImg, ...
                                                    rosPc, ...
                                                    cameraInfo,...
                                                    cameraToLidarTransform,...
                                                    lidarToVboxTransformation,...
                                                    invertLidarZRot, ...
                                                    correctColor, ...
                                                    odomMsg, ...
                                                    gridBuilder, ...
                                                    segmentationModel, ...
                                                    lidarProcessingModel, ...
                                                    convertNEDToENU);

end