// Generated by gencpp from file avt_341_msgs/BoundingBox2d.msg
// DO NOT EDIT!


#ifndef AVT_341_MSGS_MESSAGE_BOUNDINGBOX2D_H
#define AVT_341_MSGS_MESSAGE_BOUNDINGBOX2D_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace avt_341_msgs
{
template <class ContainerAllocator>
struct BoundingBox2d_
{
  typedef BoundingBox2d_<ContainerAllocator> Type;

  BoundingBox2d_()
    : x_min(0)
    , x_max(0)
    , y_min(0)
    , y_max(0)  {
    }
  BoundingBox2d_(const ContainerAllocator& _alloc)
    : x_min(0)
    , x_max(0)
    , y_min(0)
    , y_max(0)  {
  (void)_alloc;
    }



   typedef int32_t _x_min_type;
  _x_min_type x_min;

   typedef int32_t _x_max_type;
  _x_max_type x_max;

   typedef int32_t _y_min_type;
  _y_min_type y_min;

   typedef int32_t _y_max_type;
  _y_max_type y_max;





  typedef boost::shared_ptr< ::avt_341_msgs::BoundingBox2d_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::avt_341_msgs::BoundingBox2d_<ContainerAllocator> const> ConstPtr;

}; // struct BoundingBox2d_

typedef ::avt_341_msgs::BoundingBox2d_<std::allocator<void> > BoundingBox2d;

typedef boost::shared_ptr< ::avt_341_msgs::BoundingBox2d > BoundingBox2dPtr;
typedef boost::shared_ptr< ::avt_341_msgs::BoundingBox2d const> BoundingBox2dConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::avt_341_msgs::BoundingBox2d_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::avt_341_msgs::BoundingBox2d_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::avt_341_msgs::BoundingBox2d_<ContainerAllocator1> & lhs, const ::avt_341_msgs::BoundingBox2d_<ContainerAllocator2> & rhs)
{
  return lhs.x_min == rhs.x_min &&
    lhs.x_max == rhs.x_max &&
    lhs.y_min == rhs.y_min &&
    lhs.y_max == rhs.y_max;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::avt_341_msgs::BoundingBox2d_<ContainerAllocator1> & lhs, const ::avt_341_msgs::BoundingBox2d_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace avt_341_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::avt_341_msgs::BoundingBox2d_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::avt_341_msgs::BoundingBox2d_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::avt_341_msgs::BoundingBox2d_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::avt_341_msgs::BoundingBox2d_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avt_341_msgs::BoundingBox2d_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avt_341_msgs::BoundingBox2d_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::avt_341_msgs::BoundingBox2d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da93b905cb7f2e0b04662214969ec2ff";
  }

  static const char* value(const ::avt_341_msgs::BoundingBox2d_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda93b905cb7f2e0bULL;
  static const uint64_t static_value2 = 0x04662214969ec2ffULL;
};

template<class ContainerAllocator>
struct DataType< ::avt_341_msgs::BoundingBox2d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "avt_341_msgs/BoundingBox2d";
  }

  static const char* value(const ::avt_341_msgs::BoundingBox2d_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::avt_341_msgs::BoundingBox2d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message represents a two-dimensional bounding box enclosing a region of\n"
"# the image frame where an object detector has formulated a hypothesis. The\n"
"# bounding box is aligned to image frame and may not be rotated, hence it is\n"
"# uniquely defined by its four corners.\n"
"#\n"
"# This message is not stamped, as it is meant to be part of a message including\n"
"# all detections provided by an object detector for a given image.\n"
"\n"
"# Minimum x coordinate of the bounding box in pixels.\n"
"int32 x_min\n"
"\n"
"# Maximum x coordinate of the bounding box in pixels.\n"
"int32 x_max\n"
"\n"
"# Minimum y coordinate of the bounding box in pixels.\n"
"int32 y_min\n"
"\n"
"# Maximum y coordinate of the bounding box in pixels.\n"
"int32 y_max\n"
;
  }

  static const char* value(const ::avt_341_msgs::BoundingBox2d_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::avt_341_msgs::BoundingBox2d_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x_min);
      stream.next(m.x_max);
      stream.next(m.y_min);
      stream.next(m.y_max);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoundingBox2d_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::avt_341_msgs::BoundingBox2d_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::avt_341_msgs::BoundingBox2d_<ContainerAllocator>& v)
  {
    s << indent << "x_min: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x_min);
    s << indent << "x_max: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x_max);
    s << indent << "y_min: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y_min);
    s << indent << "y_max: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y_max);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AVT_341_MSGS_MESSAGE_BOUNDINGBOX2D_H
