// Generated by gencpp from file avt_341_msgs/Communication.msg
// DO NOT EDIT!


#ifndef AVT_341_MSGS_MESSAGE_COMMUNICATION_H
#define AVT_341_MSGS_MESSAGE_COMMUNICATION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace avt_341_msgs
{
template <class ContainerAllocator>
struct Communication_
{
  typedef Communication_<ContainerAllocator> Type;

  Communication_()
    : sender_name()
    , msg_id(0)
    , type()
    , formation()
    , receiver_name()
    , leader_name()
    , follower1_name()
    , follower2_name()
    , follower3_name()
    , objective_name()
    , desired_speed(0.0)
    , priority_type()
    , termination_method()
    , x_scale(0.0)
    , y_scale(0.0)
    , x_offset(0.0)
    , y_offset(0.0)
    , distance(0.0)
    , target_msg_id(0)  {
    }
  Communication_(const ContainerAllocator& _alloc)
    : sender_name(_alloc)
    , msg_id(0)
    , type(_alloc)
    , formation(_alloc)
    , receiver_name(_alloc)
    , leader_name(_alloc)
    , follower1_name(_alloc)
    , follower2_name(_alloc)
    , follower3_name(_alloc)
    , objective_name(_alloc)
    , desired_speed(0.0)
    , priority_type(_alloc)
    , termination_method(_alloc)
    , x_scale(0.0)
    , y_scale(0.0)
    , x_offset(0.0)
    , y_offset(0.0)
    , distance(0.0)
    , target_msg_id(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _sender_name_type;
  _sender_name_type sender_name;

   typedef int32_t _msg_id_type;
  _msg_id_type msg_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _type_type;
  _type_type type;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _formation_type;
  _formation_type formation;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _receiver_name_type;
  _receiver_name_type receiver_name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _leader_name_type;
  _leader_name_type leader_name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _follower1_name_type;
  _follower1_name_type follower1_name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _follower2_name_type;
  _follower2_name_type follower2_name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _follower3_name_type;
  _follower3_name_type follower3_name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _objective_name_type;
  _objective_name_type objective_name;

   typedef double _desired_speed_type;
  _desired_speed_type desired_speed;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _priority_type_type;
  _priority_type_type priority_type;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _termination_method_type;
  _termination_method_type termination_method;

   typedef double _x_scale_type;
  _x_scale_type x_scale;

   typedef double _y_scale_type;
  _y_scale_type y_scale;

   typedef double _x_offset_type;
  _x_offset_type x_offset;

   typedef double _y_offset_type;
  _y_offset_type y_offset;

   typedef double _distance_type;
  _distance_type distance;

   typedef int32_t _target_msg_id_type;
  _target_msg_id_type target_msg_id;





  typedef boost::shared_ptr< ::avt_341_msgs::Communication_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::avt_341_msgs::Communication_<ContainerAllocator> const> ConstPtr;

}; // struct Communication_

typedef ::avt_341_msgs::Communication_<std::allocator<void> > Communication;

typedef boost::shared_ptr< ::avt_341_msgs::Communication > CommunicationPtr;
typedef boost::shared_ptr< ::avt_341_msgs::Communication const> CommunicationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::avt_341_msgs::Communication_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::avt_341_msgs::Communication_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::avt_341_msgs::Communication_<ContainerAllocator1> & lhs, const ::avt_341_msgs::Communication_<ContainerAllocator2> & rhs)
{
  return lhs.sender_name == rhs.sender_name &&
    lhs.msg_id == rhs.msg_id &&
    lhs.type == rhs.type &&
    lhs.formation == rhs.formation &&
    lhs.receiver_name == rhs.receiver_name &&
    lhs.leader_name == rhs.leader_name &&
    lhs.follower1_name == rhs.follower1_name &&
    lhs.follower2_name == rhs.follower2_name &&
    lhs.follower3_name == rhs.follower3_name &&
    lhs.objective_name == rhs.objective_name &&
    lhs.desired_speed == rhs.desired_speed &&
    lhs.priority_type == rhs.priority_type &&
    lhs.termination_method == rhs.termination_method &&
    lhs.x_scale == rhs.x_scale &&
    lhs.y_scale == rhs.y_scale &&
    lhs.x_offset == rhs.x_offset &&
    lhs.y_offset == rhs.y_offset &&
    lhs.distance == rhs.distance &&
    lhs.target_msg_id == rhs.target_msg_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::avt_341_msgs::Communication_<ContainerAllocator1> & lhs, const ::avt_341_msgs::Communication_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace avt_341_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::avt_341_msgs::Communication_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::avt_341_msgs::Communication_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::avt_341_msgs::Communication_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::avt_341_msgs::Communication_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avt_341_msgs::Communication_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avt_341_msgs::Communication_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::avt_341_msgs::Communication_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b7d0b7fede5233ad75ab393a95ddc673";
  }

  static const char* value(const ::avt_341_msgs::Communication_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb7d0b7fede5233adULL;
  static const uint64_t static_value2 = 0x75ab393a95ddc673ULL;
};

template<class ContainerAllocator>
struct DataType< ::avt_341_msgs::Communication_<ContainerAllocator> >
{
  static const char* value()
  {
    return "avt_341_msgs/Communication";
  }

  static const char* value(const ::avt_341_msgs::Communication_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::avt_341_msgs::Communication_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string sender_name\n"
"int32 msg_id\n"
"string type\n"
"string formation\n"
"string receiver_name\n"
"string leader_name\n"
"string follower1_name\n"
"string follower2_name\n"
"string follower3_name\n"
"string objective_name\n"
"float64 desired_speed\n"
"string priority_type\n"
"string termination_method\n"
"float64 x_scale\n"
"float64 y_scale\n"
"float64 x_offset\n"
"float64 y_offset\n"
"float64 distance\n"
"int32 target_msg_id\n"
;
  }

  static const char* value(const ::avt_341_msgs::Communication_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::avt_341_msgs::Communication_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sender_name);
      stream.next(m.msg_id);
      stream.next(m.type);
      stream.next(m.formation);
      stream.next(m.receiver_name);
      stream.next(m.leader_name);
      stream.next(m.follower1_name);
      stream.next(m.follower2_name);
      stream.next(m.follower3_name);
      stream.next(m.objective_name);
      stream.next(m.desired_speed);
      stream.next(m.priority_type);
      stream.next(m.termination_method);
      stream.next(m.x_scale);
      stream.next(m.y_scale);
      stream.next(m.x_offset);
      stream.next(m.y_offset);
      stream.next(m.distance);
      stream.next(m.target_msg_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Communication_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::avt_341_msgs::Communication_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::avt_341_msgs::Communication_<ContainerAllocator>& v)
  {
    s << indent << "sender_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.sender_name);
    s << indent << "msg_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.msg_id);
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.type);
    s << indent << "formation: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.formation);
    s << indent << "receiver_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.receiver_name);
    s << indent << "leader_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.leader_name);
    s << indent << "follower1_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.follower1_name);
    s << indent << "follower2_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.follower2_name);
    s << indent << "follower3_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.follower3_name);
    s << indent << "objective_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.objective_name);
    s << indent << "desired_speed: ";
    Printer<double>::stream(s, indent + "  ", v.desired_speed);
    s << indent << "priority_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.priority_type);
    s << indent << "termination_method: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.termination_method);
    s << indent << "x_scale: ";
    Printer<double>::stream(s, indent + "  ", v.x_scale);
    s << indent << "y_scale: ";
    Printer<double>::stream(s, indent + "  ", v.y_scale);
    s << indent << "x_offset: ";
    Printer<double>::stream(s, indent + "  ", v.x_offset);
    s << indent << "y_offset: ";
    Printer<double>::stream(s, indent + "  ", v.y_offset);
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
    s << indent << "target_msg_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.target_msg_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AVT_341_MSGS_MESSAGE_COMMUNICATION_H
