// Generated by gencpp from file avt_341_msgs/DwaInfo.msg
// DO NOT EDIT!


#ifndef AVT_341_MSGS_MESSAGE_DWAINFO_H
#define AVT_341_MSGS_MESSAGE_DWAINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <avt_341_msgs/DwaTrajectory.h>
#include <avt_341_msgs/DwaTrajectory.h>

namespace avt_341_msgs
{
template <class ContainerAllocator>
struct DwaInfo_
{
  typedef DwaInfo_<ContainerAllocator> Type;

  DwaInfo_()
    : header()
    , optimal_trajectory()
    , planned_trajectories()  {
    }
  DwaInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , optimal_trajectory(_alloc)
    , planned_trajectories(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::avt_341_msgs::DwaTrajectory_<ContainerAllocator>  _optimal_trajectory_type;
  _optimal_trajectory_type optimal_trajectory;

   typedef std::vector< ::avt_341_msgs::DwaTrajectory_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::avt_341_msgs::DwaTrajectory_<ContainerAllocator> >> _planned_trajectories_type;
  _planned_trajectories_type planned_trajectories;





  typedef boost::shared_ptr< ::avt_341_msgs::DwaInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::avt_341_msgs::DwaInfo_<ContainerAllocator> const> ConstPtr;

}; // struct DwaInfo_

typedef ::avt_341_msgs::DwaInfo_<std::allocator<void> > DwaInfo;

typedef boost::shared_ptr< ::avt_341_msgs::DwaInfo > DwaInfoPtr;
typedef boost::shared_ptr< ::avt_341_msgs::DwaInfo const> DwaInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::avt_341_msgs::DwaInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::avt_341_msgs::DwaInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::avt_341_msgs::DwaInfo_<ContainerAllocator1> & lhs, const ::avt_341_msgs::DwaInfo_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.optimal_trajectory == rhs.optimal_trajectory &&
    lhs.planned_trajectories == rhs.planned_trajectories;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::avt_341_msgs::DwaInfo_<ContainerAllocator1> & lhs, const ::avt_341_msgs::DwaInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace avt_341_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::avt_341_msgs::DwaInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::avt_341_msgs::DwaInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::avt_341_msgs::DwaInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::avt_341_msgs::DwaInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avt_341_msgs::DwaInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avt_341_msgs::DwaInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::avt_341_msgs::DwaInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bda53ade1812b34f2bb2ce8584d13baa";
  }

  static const char* value(const ::avt_341_msgs::DwaInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbda53ade1812b34fULL;
  static const uint64_t static_value2 = 0x2bb2ce8584d13baaULL;
};

template<class ContainerAllocator>
struct DataType< ::avt_341_msgs::DwaInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "avt_341_msgs/DwaInfo";
  }

  static const char* value(const ::avt_341_msgs::DwaInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::avt_341_msgs::DwaInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"# This message contains planning step recap information for the Dynamic Window\n"
"# Approach (DWA) planner.\n"
"\n"
"# Stamped header for the planner completion time.\n"
"std_msgs/Header header\n"
"\n"
"# The optimal trajectory for this planning step.\n"
"DwaTrajectory optimal_trajectory\n"
"\n"
"# Array of planned trajectories. This field is optional and may not be populated\n"
"# based on planner settings. When provided, this field contains all planned\n"
"# trajectories, including the optimal one.\n"
"DwaTrajectory[] planned_trajectories\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: avt_341_msgs/DwaTrajectory\n"
"# This message contains information on a simulated trajectory generated and\n"
"# evaluated by the Dynamic Window Approach (DWA) planner.\n"
"\n"
"# Predicted path for the simulated trajectory. \n"
"nav_msgs/Path path\n"
"\n"
"# The individual cost term values for the objective function across the entire\n"
"# trajectory. The values contained in this field are already scaled by the planner\n"
"# weights.\n"
"DwaObjective objective\n"
"\n"
"# Cumulative cost for all objective function cost terms after scaling. This\n"
"# field is equivalent to the sum of all the individual terms contained in the\n"
"# objective function message. \n"
"float64 cost\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/Path\n"
"#An array of poses that represents a Path for a robot to follow\n"
"Header header\n"
"geometry_msgs/PoseStamped[] poses\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: avt_341_msgs/DwaObjective\n"
"# This message contains the individual objective function cost terms values for\n"
"# a trajectory planned by the Dynamic Window Approach (DWA) planner. All cost\n"
"# terms in this message are already scaled by the user-defined weight factors.\n"
"\n"
"# Goal progress cost term.\n"
"float64 goal_cost\n"
"\n"
"# Obstacle avoidance cost term.\n"
"float64 obstacle_cost\n"
"\n"
"# Segmentation grid cost term.\n"
"float64 segmentation_cost\n"
"\n"
"# Heading deviation cost term.\n"
"float64 heading_cost\n"
"\n"
"# Target speed deviation cost term.\n"
"float64 speed_cost\n"
"\n"
"# Current trajectory deviation cost term.\n"
"float64 deviation_cost\n"
;
  }

  static const char* value(const ::avt_341_msgs::DwaInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::avt_341_msgs::DwaInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.optimal_trajectory);
      stream.next(m.planned_trajectories);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DwaInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::avt_341_msgs::DwaInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::avt_341_msgs::DwaInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "optimal_trajectory: ";
    s << std::endl;
    Printer< ::avt_341_msgs::DwaTrajectory_<ContainerAllocator> >::stream(s, indent + "  ", v.optimal_trajectory);
    s << indent << "planned_trajectories[]" << std::endl;
    for (size_t i = 0; i < v.planned_trajectories.size(); ++i)
    {
      s << indent << "  planned_trajectories[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::avt_341_msgs::DwaTrajectory_<ContainerAllocator> >::stream(s, indent + "    ", v.planned_trajectories[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AVT_341_MSGS_MESSAGE_DWAINFO_H
