// Generated by gencpp from file avt_341_msgs/LiorfSaveMapResponse.msg
// DO NOT EDIT!


#ifndef AVT_341_MSGS_MESSAGE_LIORFSAVEMAPRESPONSE_H
#define AVT_341_MSGS_MESSAGE_LIORFSAVEMAPRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace avt_341_msgs
{
template <class ContainerAllocator>
struct LiorfSaveMapResponse_
{
  typedef LiorfSaveMapResponse_<ContainerAllocator> Type;

  LiorfSaveMapResponse_()
    : success(false)  {
    }
  LiorfSaveMapResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::avt_341_msgs::LiorfSaveMapResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::avt_341_msgs::LiorfSaveMapResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LiorfSaveMapResponse_

typedef ::avt_341_msgs::LiorfSaveMapResponse_<std::allocator<void> > LiorfSaveMapResponse;

typedef boost::shared_ptr< ::avt_341_msgs::LiorfSaveMapResponse > LiorfSaveMapResponsePtr;
typedef boost::shared_ptr< ::avt_341_msgs::LiorfSaveMapResponse const> LiorfSaveMapResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::avt_341_msgs::LiorfSaveMapResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::avt_341_msgs::LiorfSaveMapResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::avt_341_msgs::LiorfSaveMapResponse_<ContainerAllocator1> & lhs, const ::avt_341_msgs::LiorfSaveMapResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::avt_341_msgs::LiorfSaveMapResponse_<ContainerAllocator1> & lhs, const ::avt_341_msgs::LiorfSaveMapResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace avt_341_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::avt_341_msgs::LiorfSaveMapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::avt_341_msgs::LiorfSaveMapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::avt_341_msgs::LiorfSaveMapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::avt_341_msgs::LiorfSaveMapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avt_341_msgs::LiorfSaveMapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avt_341_msgs::LiorfSaveMapResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::avt_341_msgs::LiorfSaveMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::avt_341_msgs::LiorfSaveMapResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::avt_341_msgs::LiorfSaveMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "avt_341_msgs/LiorfSaveMapResponse";
  }

  static const char* value(const ::avt_341_msgs::LiorfSaveMapResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::avt_341_msgs::LiorfSaveMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::avt_341_msgs::LiorfSaveMapResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::avt_341_msgs::LiorfSaveMapResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LiorfSaveMapResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::avt_341_msgs::LiorfSaveMapResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::avt_341_msgs::LiorfSaveMapResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AVT_341_MSGS_MESSAGE_LIORFSAVEMAPRESPONSE_H
