// Generated by gencpp from file avt_341_msgs/Obstacles.msg
// DO NOT EDIT!


#ifndef AVT_341_MSGS_MESSAGE_OBSTACLES_H
#define AVT_341_MSGS_MESSAGE_OBSTACLES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace avt_341_msgs
{
template <class ContainerAllocator>
struct Obstacles_
{
  typedef Obstacles_<ContainerAllocator> Type;

  Obstacles_()
    : id(0)
    , obstacle_size_meters(0.0)
    , data()  {
    }
  Obstacles_(const ContainerAllocator& _alloc)
    : id(0)
    , obstacle_size_meters(0.0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _id_type;
  _id_type id;

   typedef double _obstacle_size_meters_type;
  _obstacle_size_meters_type obstacle_size_meters;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::avt_341_msgs::Obstacles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::avt_341_msgs::Obstacles_<ContainerAllocator> const> ConstPtr;

}; // struct Obstacles_

typedef ::avt_341_msgs::Obstacles_<std::allocator<void> > Obstacles;

typedef boost::shared_ptr< ::avt_341_msgs::Obstacles > ObstaclesPtr;
typedef boost::shared_ptr< ::avt_341_msgs::Obstacles const> ObstaclesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::avt_341_msgs::Obstacles_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::avt_341_msgs::Obstacles_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::avt_341_msgs::Obstacles_<ContainerAllocator1> & lhs, const ::avt_341_msgs::Obstacles_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.obstacle_size_meters == rhs.obstacle_size_meters &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::avt_341_msgs::Obstacles_<ContainerAllocator1> & lhs, const ::avt_341_msgs::Obstacles_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace avt_341_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::avt_341_msgs::Obstacles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::avt_341_msgs::Obstacles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::avt_341_msgs::Obstacles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::avt_341_msgs::Obstacles_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avt_341_msgs::Obstacles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avt_341_msgs::Obstacles_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::avt_341_msgs::Obstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a55c04528cfeec7dafb93064c59d2dd";
  }

  static const char* value(const ::avt_341_msgs::Obstacles_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a55c04528cfeec7ULL;
  static const uint64_t static_value2 = 0xdafb93064c59d2ddULL;
};

template<class ContainerAllocator>
struct DataType< ::avt_341_msgs::Obstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "avt_341_msgs/Obstacles";
  }

  static const char* value(const ::avt_341_msgs::Obstacles_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::avt_341_msgs::Obstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 id\n"
"float64 obstacle_size_meters\n"
"float64[] data\n"
;
  }

  static const char* value(const ::avt_341_msgs::Obstacles_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::avt_341_msgs::Obstacles_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.obstacle_size_meters);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Obstacles_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::avt_341_msgs::Obstacles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::avt_341_msgs::Obstacles_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.id);
    s << indent << "obstacle_size_meters: ";
    Printer<double>::stream(s, indent + "  ", v.obstacle_size_meters);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AVT_341_MSGS_MESSAGE_OBSTACLES_H
