// Generated by gencpp from file avt_341_msgs/OccupiedCell.msg
// DO NOT EDIT!


#ifndef AVT_341_MSGS_MESSAGE_OCCUPIEDCELL_H
#define AVT_341_MSGS_MESSAGE_OCCUPIEDCELL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace avt_341_msgs
{
template <class ContainerAllocator>
struct OccupiedCell_
{
  typedef OccupiedCell_<ContainerAllocator> Type;

  OccupiedCell_()
    : x_index(0)
    , y_index(0)
    , data(0)  {
    }
  OccupiedCell_(const ContainerAllocator& _alloc)
    : x_index(0)
    , y_index(0)
    , data(0)  {
  (void)_alloc;
    }



   typedef uint32_t _x_index_type;
  _x_index_type x_index;

   typedef uint32_t _y_index_type;
  _y_index_type y_index;

   typedef int8_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::avt_341_msgs::OccupiedCell_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::avt_341_msgs::OccupiedCell_<ContainerAllocator> const> ConstPtr;

}; // struct OccupiedCell_

typedef ::avt_341_msgs::OccupiedCell_<std::allocator<void> > OccupiedCell;

typedef boost::shared_ptr< ::avt_341_msgs::OccupiedCell > OccupiedCellPtr;
typedef boost::shared_ptr< ::avt_341_msgs::OccupiedCell const> OccupiedCellConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::avt_341_msgs::OccupiedCell_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::avt_341_msgs::OccupiedCell_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::avt_341_msgs::OccupiedCell_<ContainerAllocator1> & lhs, const ::avt_341_msgs::OccupiedCell_<ContainerAllocator2> & rhs)
{
  return lhs.x_index == rhs.x_index &&
    lhs.y_index == rhs.y_index &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::avt_341_msgs::OccupiedCell_<ContainerAllocator1> & lhs, const ::avt_341_msgs::OccupiedCell_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace avt_341_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::avt_341_msgs::OccupiedCell_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::avt_341_msgs::OccupiedCell_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::avt_341_msgs::OccupiedCell_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::avt_341_msgs::OccupiedCell_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avt_341_msgs::OccupiedCell_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avt_341_msgs::OccupiedCell_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::avt_341_msgs::OccupiedCell_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3364ced6c6173e4d6f7f283e1479eee9";
  }

  static const char* value(const ::avt_341_msgs::OccupiedCell_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3364ced6c6173e4dULL;
  static const uint64_t static_value2 = 0x6f7f283e1479eee9ULL;
};

template<class ContainerAllocator>
struct DataType< ::avt_341_msgs::OccupiedCell_<ContainerAllocator> >
{
  static const char* value()
  {
    return "avt_341_msgs/OccupiedCell";
  }

  static const char* value(const ::avt_341_msgs::OccupiedCell_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::avt_341_msgs::OccupiedCell_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 x_index\n"
"uint32 y_index\n"
"int8 data\n"
;
  }

  static const char* value(const ::avt_341_msgs::OccupiedCell_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::avt_341_msgs::OccupiedCell_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x_index);
      stream.next(m.y_index);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OccupiedCell_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::avt_341_msgs::OccupiedCell_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::avt_341_msgs::OccupiedCell_<ContainerAllocator>& v)
  {
    s << indent << "x_index: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.x_index);
    s << indent << "y_index: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.y_index);
    s << indent << "data: ";
    Printer<int8_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AVT_341_MSGS_MESSAGE_OCCUPIEDCELL_H
