// Generated by gencpp from file avt_341_msgs/Sinkage.msg
// DO NOT EDIT!


#ifndef AVT_341_MSGS_MESSAGE_SINKAGE_H
#define AVT_341_MSGS_MESSAGE_SINKAGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace avt_341_msgs
{
template <class ContainerAllocator>
struct Sinkage_
{
  typedef Sinkage_<ContainerAllocator> Type;

  Sinkage_()
    : n(0.0)  {
    }
  Sinkage_(const ContainerAllocator& _alloc)
    : n(0.0)  {
  (void)_alloc;
    }



   typedef double _n_type;
  _n_type n;





  typedef boost::shared_ptr< ::avt_341_msgs::Sinkage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::avt_341_msgs::Sinkage_<ContainerAllocator> const> ConstPtr;

}; // struct Sinkage_

typedef ::avt_341_msgs::Sinkage_<std::allocator<void> > Sinkage;

typedef boost::shared_ptr< ::avt_341_msgs::Sinkage > SinkagePtr;
typedef boost::shared_ptr< ::avt_341_msgs::Sinkage const> SinkageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::avt_341_msgs::Sinkage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::avt_341_msgs::Sinkage_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::avt_341_msgs::Sinkage_<ContainerAllocator1> & lhs, const ::avt_341_msgs::Sinkage_<ContainerAllocator2> & rhs)
{
  return lhs.n == rhs.n;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::avt_341_msgs::Sinkage_<ContainerAllocator1> & lhs, const ::avt_341_msgs::Sinkage_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace avt_341_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::avt_341_msgs::Sinkage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::avt_341_msgs::Sinkage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::avt_341_msgs::Sinkage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::avt_341_msgs::Sinkage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avt_341_msgs::Sinkage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avt_341_msgs::Sinkage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::avt_341_msgs::Sinkage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "65f0673a55739dec984a47bd3a9c8f0d";
  }

  static const char* value(const ::avt_341_msgs::Sinkage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x65f0673a55739decULL;
  static const uint64_t static_value2 = 0x984a47bd3a9c8f0dULL;
};

template<class ContainerAllocator>
struct DataType< ::avt_341_msgs::Sinkage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "avt_341_msgs/Sinkage";
  }

  static const char* value(const ::avt_341_msgs::Sinkage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::avt_341_msgs::Sinkage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 n\n"
;
  }

  static const char* value(const ::avt_341_msgs::Sinkage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::avt_341_msgs::Sinkage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.n);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Sinkage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::avt_341_msgs::Sinkage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::avt_341_msgs::Sinkage_<ContainerAllocator>& v)
  {
    s << indent << "n: ";
    Printer<double>::stream(s, indent + "  ", v.n);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AVT_341_MSGS_MESSAGE_SINKAGE_H
