<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>avt_341_msgs</name>
  <version>0.0.0</version>
  <description>AVT-341 autonomy stack messages</description>

  <maintainer email="cgoodin@cavs.msstate.edu">Chris Goodin</maintainer>
  <maintainer email="dsi@mpe.au.dk">Dario Sirangelo</maintainer>

  <author email="cgoodin@cavs.msstate.edu">Chris Goodin</author>
  <author email="dwc2@cavs.msstate.edu">Daniel Carruth</author>

  <license>TODO</license>

  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>visualization_msgs</depend>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>rosidl_default_generators</build_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
    <ros1_bridge mapping_rules="ros_bridge_mappings.yaml" />
  </export>
</package>