# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from avt_341_msgs/Communication.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Communication(genpy.Message):
  _md5sum = "b7d0b7fede5233ad75ab393a95ddc673"
  _type = "avt_341_msgs/Communication"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string sender_name
int32 msg_id
string type
string formation
string receiver_name
string leader_name
string follower1_name
string follower2_name
string follower3_name
string objective_name
float64 desired_speed
string priority_type
string termination_method
float64 x_scale
float64 y_scale
float64 x_offset
float64 y_offset
float64 distance
int32 target_msg_id"""
  __slots__ = ['sender_name','msg_id','type','formation','receiver_name','leader_name','follower1_name','follower2_name','follower3_name','objective_name','desired_speed','priority_type','termination_method','x_scale','y_scale','x_offset','y_offset','distance','target_msg_id']
  _slot_types = ['string','int32','string','string','string','string','string','string','string','string','float64','string','string','float64','float64','float64','float64','float64','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       sender_name,msg_id,type,formation,receiver_name,leader_name,follower1_name,follower2_name,follower3_name,objective_name,desired_speed,priority_type,termination_method,x_scale,y_scale,x_offset,y_offset,distance,target_msg_id

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Communication, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.sender_name is None:
        self.sender_name = ''
      if self.msg_id is None:
        self.msg_id = 0
      if self.type is None:
        self.type = ''
      if self.formation is None:
        self.formation = ''
      if self.receiver_name is None:
        self.receiver_name = ''
      if self.leader_name is None:
        self.leader_name = ''
      if self.follower1_name is None:
        self.follower1_name = ''
      if self.follower2_name is None:
        self.follower2_name = ''
      if self.follower3_name is None:
        self.follower3_name = ''
      if self.objective_name is None:
        self.objective_name = ''
      if self.desired_speed is None:
        self.desired_speed = 0.
      if self.priority_type is None:
        self.priority_type = ''
      if self.termination_method is None:
        self.termination_method = ''
      if self.x_scale is None:
        self.x_scale = 0.
      if self.y_scale is None:
        self.y_scale = 0.
      if self.x_offset is None:
        self.x_offset = 0.
      if self.y_offset is None:
        self.y_offset = 0.
      if self.distance is None:
        self.distance = 0.
      if self.target_msg_id is None:
        self.target_msg_id = 0
    else:
      self.sender_name = ''
      self.msg_id = 0
      self.type = ''
      self.formation = ''
      self.receiver_name = ''
      self.leader_name = ''
      self.follower1_name = ''
      self.follower2_name = ''
      self.follower3_name = ''
      self.objective_name = ''
      self.desired_speed = 0.
      self.priority_type = ''
      self.termination_method = ''
      self.x_scale = 0.
      self.y_scale = 0.
      self.x_offset = 0.
      self.y_offset = 0.
      self.distance = 0.
      self.target_msg_id = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.sender_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.msg_id
      buff.write(_get_struct_i().pack(_x))
      _x = self.type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.formation
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.receiver_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.leader_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.follower1_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.follower2_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.follower3_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.objective_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.desired_speed
      buff.write(_get_struct_d().pack(_x))
      _x = self.priority_type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.termination_method
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_5di().pack(_x.x_scale, _x.y_scale, _x.x_offset, _x.y_offset, _x.distance, _x.target_msg_id))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.sender_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.sender_name = str[start:end]
      start = end
      end += 4
      (self.msg_id,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.type = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.formation = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.formation = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.receiver_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.receiver_name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.leader_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.leader_name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.follower1_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.follower1_name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.follower2_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.follower2_name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.follower3_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.follower3_name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.objective_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.objective_name = str[start:end]
      start = end
      end += 8
      (self.desired_speed,) = _get_struct_d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.priority_type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.priority_type = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.termination_method = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.termination_method = str[start:end]
      _x = self
      start = end
      end += 44
      (_x.x_scale, _x.y_scale, _x.x_offset, _x.y_offset, _x.distance, _x.target_msg_id,) = _get_struct_5di().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.sender_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.msg_id
      buff.write(_get_struct_i().pack(_x))
      _x = self.type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.formation
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.receiver_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.leader_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.follower1_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.follower2_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.follower3_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.objective_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.desired_speed
      buff.write(_get_struct_d().pack(_x))
      _x = self.priority_type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.termination_method
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_5di().pack(_x.x_scale, _x.y_scale, _x.x_offset, _x.y_offset, _x.distance, _x.target_msg_id))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.sender_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.sender_name = str[start:end]
      start = end
      end += 4
      (self.msg_id,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.type = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.formation = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.formation = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.receiver_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.receiver_name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.leader_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.leader_name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.follower1_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.follower1_name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.follower2_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.follower2_name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.follower3_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.follower3_name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.objective_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.objective_name = str[start:end]
      start = end
      end += 8
      (self.desired_speed,) = _get_struct_d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.priority_type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.priority_type = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.termination_method = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.termination_method = str[start:end]
      _x = self
      start = end
      end += 44
      (_x.x_scale, _x.y_scale, _x.x_offset, _x.y_offset, _x.distance, _x.target_msg_id,) = _get_struct_5di().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5di = None
def _get_struct_5di():
    global _struct_5di
    if _struct_5di is None:
        _struct_5di = struct.Struct("<5di")
    return _struct_5di
_struct_d = None
def _get_struct_d():
    global _struct_d
    if _struct_d is None:
        _struct_d = struct.Struct("<d")
    return _struct_d
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
