# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from avt_341_msgs/DwaObjective.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class DwaObjective(genpy.Message):
  _md5sum = "0c23918921b89b7797bde9cc90d54688"
  _type = "avt_341_msgs/DwaObjective"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# This message contains the individual objective function cost terms values for
# a trajectory planned by the Dynamic Window Approach (DWA) planner. All cost
# terms in this message are already scaled by the user-defined weight factors.

# Goal progress cost term.
float64 goal_cost

# Obstacle avoidance cost term.
float64 obstacle_cost

# Segmentation grid cost term.
float64 segmentation_cost

# Heading deviation cost term.
float64 heading_cost

# Target speed deviation cost term.
float64 speed_cost

# Current trajectory deviation cost term.
float64 deviation_cost"""
  __slots__ = ['goal_cost','obstacle_cost','segmentation_cost','heading_cost','speed_cost','deviation_cost']
  _slot_types = ['float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       goal_cost,obstacle_cost,segmentation_cost,heading_cost,speed_cost,deviation_cost

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DwaObjective, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.goal_cost is None:
        self.goal_cost = 0.
      if self.obstacle_cost is None:
        self.obstacle_cost = 0.
      if self.segmentation_cost is None:
        self.segmentation_cost = 0.
      if self.heading_cost is None:
        self.heading_cost = 0.
      if self.speed_cost is None:
        self.speed_cost = 0.
      if self.deviation_cost is None:
        self.deviation_cost = 0.
    else:
      self.goal_cost = 0.
      self.obstacle_cost = 0.
      self.segmentation_cost = 0.
      self.heading_cost = 0.
      self.speed_cost = 0.
      self.deviation_cost = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.goal_cost, _x.obstacle_cost, _x.segmentation_cost, _x.heading_cost, _x.speed_cost, _x.deviation_cost))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.goal_cost, _x.obstacle_cost, _x.segmentation_cost, _x.heading_cost, _x.speed_cost, _x.deviation_cost,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.goal_cost, _x.obstacle_cost, _x.segmentation_cost, _x.heading_cost, _x.speed_cost, _x.deviation_cost))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.goal_cost, _x.obstacle_cost, _x.segmentation_cost, _x.heading_cost, _x.speed_cost, _x.deviation_cost,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
