# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from avt_341_msgs/DwaInfo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import avt_341_msgs.msg
import geometry_msgs.msg
import nav_msgs.msg
import std_msgs.msg

class DwaInfo(genpy.Message):
  _md5sum = "bda53ade1812b34f2bb2ce8584d13baa"
  _type = "avt_341_msgs/DwaInfo"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """
# This message contains planning step recap information for the Dynamic Window
# Approach (DWA) planner.

# Stamped header for the planner completion time.
std_msgs/Header header

# The optimal trajectory for this planning step.
DwaTrajectory optimal_trajectory

# Array of planned trajectories. This field is optional and may not be populated
# based on planner settings. When provided, this field contains all planned
# trajectories, including the optimal one.
DwaTrajectory[] planned_trajectories

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: avt_341_msgs/DwaTrajectory
# This message contains information on a simulated trajectory generated and
# evaluated by the Dynamic Window Approach (DWA) planner.

# Predicted path for the simulated trajectory. 
nav_msgs/Path path

# The individual cost term values for the objective function across the entire
# trajectory. The values contained in this field are already scaled by the planner
# weights.
DwaObjective objective

# Cumulative cost for all objective function cost terms after scaling. This
# field is equivalent to the sum of all the individual terms contained in the
# objective function message. 
float64 cost

================================================================================
MSG: nav_msgs/Path
#An array of poses that represents a Path for a robot to follow
Header header
geometry_msgs/PoseStamped[] poses

================================================================================
MSG: geometry_msgs/PoseStamped
# A Pose with reference coordinate frame and timestamp
Header header
Pose pose

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: avt_341_msgs/DwaObjective
# This message contains the individual objective function cost terms values for
# a trajectory planned by the Dynamic Window Approach (DWA) planner. All cost
# terms in this message are already scaled by the user-defined weight factors.

# Goal progress cost term.
float64 goal_cost

# Obstacle avoidance cost term.
float64 obstacle_cost

# Segmentation grid cost term.
float64 segmentation_cost

# Heading deviation cost term.
float64 heading_cost

# Target speed deviation cost term.
float64 speed_cost

# Current trajectory deviation cost term.
float64 deviation_cost"""
  __slots__ = ['header','optimal_trajectory','planned_trajectories']
  _slot_types = ['std_msgs/Header','avt_341_msgs/DwaTrajectory','avt_341_msgs/DwaTrajectory[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,optimal_trajectory,planned_trajectories

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DwaInfo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.optimal_trajectory is None:
        self.optimal_trajectory = avt_341_msgs.msg.DwaTrajectory()
      if self.planned_trajectories is None:
        self.planned_trajectories = []
    else:
      self.header = std_msgs.msg.Header()
      self.optimal_trajectory = avt_341_msgs.msg.DwaTrajectory()
      self.planned_trajectories = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.optimal_trajectory.path.header.seq, _x.optimal_trajectory.path.header.stamp.secs, _x.optimal_trajectory.path.header.stamp.nsecs))
      _x = self.optimal_trajectory.path.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.optimal_trajectory.path.poses)
      buff.write(_struct_I.pack(length))
      for val1 in self.optimal_trajectory.path.poses:
        _v1 = val1.header
        _x = _v1.seq
        buff.write(_get_struct_I().pack(_x))
        _v2 = _v1.stamp
        _x = _v2
        buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
        _x = _v1.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v3 = val1.pose
        _v4 = _v3.position
        _x = _v4
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v5 = _v3.orientation
        _x = _v5
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
      _x = self
      buff.write(_get_struct_7d().pack(_x.optimal_trajectory.objective.goal_cost, _x.optimal_trajectory.objective.obstacle_cost, _x.optimal_trajectory.objective.segmentation_cost, _x.optimal_trajectory.objective.heading_cost, _x.optimal_trajectory.objective.speed_cost, _x.optimal_trajectory.objective.deviation_cost, _x.optimal_trajectory.cost))
      length = len(self.planned_trajectories)
      buff.write(_struct_I.pack(length))
      for val1 in self.planned_trajectories:
        _v6 = val1.path
        _v7 = _v6.header
        _x = _v7.seq
        buff.write(_get_struct_I().pack(_x))
        _v8 = _v7.stamp
        _x = _v8
        buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
        _x = _v7.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        length = len(_v6.poses)
        buff.write(_struct_I.pack(length))
        for val3 in _v6.poses:
          _v9 = val3.header
          _x = _v9.seq
          buff.write(_get_struct_I().pack(_x))
          _v10 = _v9.stamp
          _x = _v10
          buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
          _x = _v9.frame_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _v11 = val3.pose
          _v12 = _v11.position
          _x = _v12
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _v13 = _v11.orientation
          _x = _v13
          buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
        _v14 = val1.objective
        _x = _v14
        buff.write(_get_struct_6d().pack(_x.goal_cost, _x.obstacle_cost, _x.segmentation_cost, _x.heading_cost, _x.speed_cost, _x.deviation_cost))
        _x = val1.cost
        buff.write(_get_struct_d().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.optimal_trajectory is None:
        self.optimal_trajectory = avt_341_msgs.msg.DwaTrajectory()
      if self.planned_trajectories is None:
        self.planned_trajectories = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.optimal_trajectory.path.header.seq, _x.optimal_trajectory.path.header.stamp.secs, _x.optimal_trajectory.path.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.optimal_trajectory.path.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.optimal_trajectory.path.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.optimal_trajectory.path.poses = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.PoseStamped()
        _v15 = val1.header
        start = end
        end += 4
        (_v15.seq,) = _get_struct_I().unpack(str[start:end])
        _v16 = _v15.stamp
        _x = _v16
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v15.frame_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v15.frame_id = str[start:end]
        _v17 = val1.pose
        _v18 = _v17.position
        _x = _v18
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v19 = _v17.orientation
        _x = _v19
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        self.optimal_trajectory.path.poses.append(val1)
      _x = self
      start = end
      end += 56
      (_x.optimal_trajectory.objective.goal_cost, _x.optimal_trajectory.objective.obstacle_cost, _x.optimal_trajectory.objective.segmentation_cost, _x.optimal_trajectory.objective.heading_cost, _x.optimal_trajectory.objective.speed_cost, _x.optimal_trajectory.objective.deviation_cost, _x.optimal_trajectory.cost,) = _get_struct_7d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.planned_trajectories = []
      for i in range(0, length):
        val1 = avt_341_msgs.msg.DwaTrajectory()
        _v20 = val1.path
        _v21 = _v20.header
        start = end
        end += 4
        (_v21.seq,) = _get_struct_I().unpack(str[start:end])
        _v22 = _v21.stamp
        _x = _v22
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v21.frame_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v21.frame_id = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v20.poses = []
        for i in range(0, length):
          val3 = geometry_msgs.msg.PoseStamped()
          _v23 = val3.header
          start = end
          end += 4
          (_v23.seq,) = _get_struct_I().unpack(str[start:end])
          _v24 = _v23.stamp
          _x = _v24
          start = end
          end += 8
          (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            _v23.frame_id = str[start:end].decode('utf-8', 'rosmsg')
          else:
            _v23.frame_id = str[start:end]
          _v25 = val3.pose
          _v26 = _v25.position
          _x = _v26
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _v27 = _v25.orientation
          _x = _v27
          start = end
          end += 32
          (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
          _v20.poses.append(val3)
        _v28 = val1.objective
        _x = _v28
        start = end
        end += 48
        (_x.goal_cost, _x.obstacle_cost, _x.segmentation_cost, _x.heading_cost, _x.speed_cost, _x.deviation_cost,) = _get_struct_6d().unpack(str[start:end])
        start = end
        end += 8
        (val1.cost,) = _get_struct_d().unpack(str[start:end])
        self.planned_trajectories.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.optimal_trajectory.path.header.seq, _x.optimal_trajectory.path.header.stamp.secs, _x.optimal_trajectory.path.header.stamp.nsecs))
      _x = self.optimal_trajectory.path.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.optimal_trajectory.path.poses)
      buff.write(_struct_I.pack(length))
      for val1 in self.optimal_trajectory.path.poses:
        _v29 = val1.header
        _x = _v29.seq
        buff.write(_get_struct_I().pack(_x))
        _v30 = _v29.stamp
        _x = _v30
        buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
        _x = _v29.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v31 = val1.pose
        _v32 = _v31.position
        _x = _v32
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v33 = _v31.orientation
        _x = _v33
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
      _x = self
      buff.write(_get_struct_7d().pack(_x.optimal_trajectory.objective.goal_cost, _x.optimal_trajectory.objective.obstacle_cost, _x.optimal_trajectory.objective.segmentation_cost, _x.optimal_trajectory.objective.heading_cost, _x.optimal_trajectory.objective.speed_cost, _x.optimal_trajectory.objective.deviation_cost, _x.optimal_trajectory.cost))
      length = len(self.planned_trajectories)
      buff.write(_struct_I.pack(length))
      for val1 in self.planned_trajectories:
        _v34 = val1.path
        _v35 = _v34.header
        _x = _v35.seq
        buff.write(_get_struct_I().pack(_x))
        _v36 = _v35.stamp
        _x = _v36
        buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
        _x = _v35.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        length = len(_v34.poses)
        buff.write(_struct_I.pack(length))
        for val3 in _v34.poses:
          _v37 = val3.header
          _x = _v37.seq
          buff.write(_get_struct_I().pack(_x))
          _v38 = _v37.stamp
          _x = _v38
          buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
          _x = _v37.frame_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _v39 = val3.pose
          _v40 = _v39.position
          _x = _v40
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _v41 = _v39.orientation
          _x = _v41
          buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
        _v42 = val1.objective
        _x = _v42
        buff.write(_get_struct_6d().pack(_x.goal_cost, _x.obstacle_cost, _x.segmentation_cost, _x.heading_cost, _x.speed_cost, _x.deviation_cost))
        _x = val1.cost
        buff.write(_get_struct_d().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.optimal_trajectory is None:
        self.optimal_trajectory = avt_341_msgs.msg.DwaTrajectory()
      if self.planned_trajectories is None:
        self.planned_trajectories = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.optimal_trajectory.path.header.seq, _x.optimal_trajectory.path.header.stamp.secs, _x.optimal_trajectory.path.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.optimal_trajectory.path.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.optimal_trajectory.path.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.optimal_trajectory.path.poses = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.PoseStamped()
        _v43 = val1.header
        start = end
        end += 4
        (_v43.seq,) = _get_struct_I().unpack(str[start:end])
        _v44 = _v43.stamp
        _x = _v44
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v43.frame_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v43.frame_id = str[start:end]
        _v45 = val1.pose
        _v46 = _v45.position
        _x = _v46
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v47 = _v45.orientation
        _x = _v47
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        self.optimal_trajectory.path.poses.append(val1)
      _x = self
      start = end
      end += 56
      (_x.optimal_trajectory.objective.goal_cost, _x.optimal_trajectory.objective.obstacle_cost, _x.optimal_trajectory.objective.segmentation_cost, _x.optimal_trajectory.objective.heading_cost, _x.optimal_trajectory.objective.speed_cost, _x.optimal_trajectory.objective.deviation_cost, _x.optimal_trajectory.cost,) = _get_struct_7d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.planned_trajectories = []
      for i in range(0, length):
        val1 = avt_341_msgs.msg.DwaTrajectory()
        _v48 = val1.path
        _v49 = _v48.header
        start = end
        end += 4
        (_v49.seq,) = _get_struct_I().unpack(str[start:end])
        _v50 = _v49.stamp
        _x = _v50
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v49.frame_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v49.frame_id = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v48.poses = []
        for i in range(0, length):
          val3 = geometry_msgs.msg.PoseStamped()
          _v51 = val3.header
          start = end
          end += 4
          (_v51.seq,) = _get_struct_I().unpack(str[start:end])
          _v52 = _v51.stamp
          _x = _v52
          start = end
          end += 8
          (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            _v51.frame_id = str[start:end].decode('utf-8', 'rosmsg')
          else:
            _v51.frame_id = str[start:end]
          _v53 = val3.pose
          _v54 = _v53.position
          _x = _v54
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _v55 = _v53.orientation
          _x = _v55
          start = end
          end += 32
          (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
          _v48.poses.append(val3)
        _v56 = val1.objective
        _x = _v56
        start = end
        end += 48
        (_x.goal_cost, _x.obstacle_cost, _x.segmentation_cost, _x.heading_cost, _x.speed_cost, _x.deviation_cost,) = _get_struct_6d().unpack(str[start:end])
        start = end
        end += 8
        (val1.cost,) = _get_struct_d().unpack(str[start:end])
        self.planned_trajectories.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
_struct_7d = None
def _get_struct_7d():
    global _struct_7d
    if _struct_7d is None:
        _struct_7d = struct.Struct("<7d")
    return _struct_7d
_struct_d = None
def _get_struct_d():
    global _struct_d
    if _struct_d is None:
        _struct_d = struct.Struct("<d")
    return _struct_d
