// Generated by gencpp from file avt_341_msgs/Detection2dArray.msg
// DO NOT EDIT!


#ifndef AVT_341_MSGS_MESSAGE_DETECTION2DARRAY_H
#define AVT_341_MSGS_MESSAGE_DETECTION2DARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <avt_341_msgs/Detection2d.h>

namespace avt_341_msgs
{
template <class ContainerAllocator>
struct Detection2dArray_
{
  typedef Detection2dArray_<ContainerAllocator> Type;

  Detection2dArray_()
    : header()
    , detections()  {
    }
  Detection2dArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , detections(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::avt_341_msgs::Detection2d_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::avt_341_msgs::Detection2d_<ContainerAllocator> >> _detections_type;
  _detections_type detections;





  typedef boost::shared_ptr< ::avt_341_msgs::Detection2dArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::avt_341_msgs::Detection2dArray_<ContainerAllocator> const> ConstPtr;

}; // struct Detection2dArray_

typedef ::avt_341_msgs::Detection2dArray_<std::allocator<void> > Detection2dArray;

typedef boost::shared_ptr< ::avt_341_msgs::Detection2dArray > Detection2dArrayPtr;
typedef boost::shared_ptr< ::avt_341_msgs::Detection2dArray const> Detection2dArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::avt_341_msgs::Detection2dArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::avt_341_msgs::Detection2dArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::avt_341_msgs::Detection2dArray_<ContainerAllocator1> & lhs, const ::avt_341_msgs::Detection2dArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.detections == rhs.detections;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::avt_341_msgs::Detection2dArray_<ContainerAllocator1> & lhs, const ::avt_341_msgs::Detection2dArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace avt_341_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::avt_341_msgs::Detection2dArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::avt_341_msgs::Detection2dArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::avt_341_msgs::Detection2dArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::avt_341_msgs::Detection2dArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avt_341_msgs::Detection2dArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avt_341_msgs::Detection2dArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::avt_341_msgs::Detection2dArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4bd5549dd2967ed5228b993c3abd5a0f";
  }

  static const char* value(const ::avt_341_msgs::Detection2dArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4bd5549dd2967ed5ULL;
  static const uint64_t static_value2 = 0x228b993c3abd5a0fULL;
};

template<class ContainerAllocator>
struct DataType< ::avt_341_msgs::Detection2dArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "avt_341_msgs/Detection2dArray";
  }

  static const char* value(const ::avt_341_msgs::Detection2dArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::avt_341_msgs::Detection2dArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message represents the results of an object detector for a given image\n"
"# frame.\n"
"\n"
"# Header stamped at the completion time of the detection.\n"
"std_msgs/Header header\n"
"\n"
"# Collection of detections for the given image frame, in the order specified by\n"
"# the image detector.\n"
"Detection2d[] detections\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: avt_341_msgs/Detection2d\n"
"# This message represents a single detection associated with an image based on\n"
"# the best scoring hypothesis after intersection-over-union (IoU) filtering.\n"
"#\n"
"# This message is not stamped, as it is meant to be part of a message including\n"
"# all detections provided by an object detector for a given image.\n"
"\n"
"# Message header.\n"
"std_msgs/Header header\n"
"\n"
"# Detection bounding box.\n"
"BoundingBox2d bounding_box\n"
"\n"
"# Detection hypothesis.\n"
"Hypothesis hypothesis\n"
"================================================================================\n"
"MSG: avt_341_msgs/BoundingBox2d\n"
"# This message represents a two-dimensional bounding box enclosing a region of\n"
"# the image frame where an object detector has formulated a hypothesis. The\n"
"# bounding box is aligned to image frame and may not be rotated, hence it is\n"
"# uniquely defined by its four corners.\n"
"#\n"
"# This message is not stamped, as it is meant to be part of a message including\n"
"# all detections provided by an object detector for a given image.\n"
"\n"
"# Minimum x coordinate of the bounding box in pixels.\n"
"int32 x_min\n"
"\n"
"# Maximum x coordinate of the bounding box in pixels.\n"
"int32 x_max\n"
"\n"
"# Minimum y coordinate of the bounding box in pixels.\n"
"int32 y_min\n"
"\n"
"# Maximum y coordinate of the bounding box in pixels.\n"
"int32 y_max\n"
"================================================================================\n"
"MSG: avt_341_msgs/Hypothesis\n"
"# This message represents an object hypothesis formulated by an object detector\n"
"# for a given region of the image.\n"
"\n"
"# The unique identifier of the object class as specified by the object detector.\n"
"int16 id\n"
"\n"
"# The human-readable label of the object class as specified by the object\n"
"# detector.\n"
"string label\n"
"\n"
"# The score associated with the hypothesis, as a floating point number between\n"
"# 0.0 and 1.0, including the limits.\n"
"float64 score\n"
;
  }

  static const char* value(const ::avt_341_msgs::Detection2dArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::avt_341_msgs::Detection2dArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.detections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Detection2dArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::avt_341_msgs::Detection2dArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::avt_341_msgs::Detection2dArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "detections[]" << std::endl;
    for (size_t i = 0; i < v.detections.size(); ++i)
    {
      s << indent << "  detections[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::avt_341_msgs::Detection2d_<ContainerAllocator> >::stream(s, indent + "    ", v.detections[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AVT_341_MSGS_MESSAGE_DETECTION2DARRAY_H
