// Generated by gencpp from file avt_341_msgs/DwaObjective.msg
// DO NOT EDIT!


#ifndef AVT_341_MSGS_MESSAGE_DWAOBJECTIVE_H
#define AVT_341_MSGS_MESSAGE_DWAOBJECTIVE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace avt_341_msgs
{
template <class ContainerAllocator>
struct DwaObjective_
{
  typedef DwaObjective_<ContainerAllocator> Type;

  DwaObjective_()
    : goal_cost(0.0)
    , obstacle_cost(0.0)
    , segmentation_cost(0.0)
    , heading_cost(0.0)
    , speed_cost(0.0)
    , deviation_cost(0.0)  {
    }
  DwaObjective_(const ContainerAllocator& _alloc)
    : goal_cost(0.0)
    , obstacle_cost(0.0)
    , segmentation_cost(0.0)
    , heading_cost(0.0)
    , speed_cost(0.0)
    , deviation_cost(0.0)  {
  (void)_alloc;
    }



   typedef double _goal_cost_type;
  _goal_cost_type goal_cost;

   typedef double _obstacle_cost_type;
  _obstacle_cost_type obstacle_cost;

   typedef double _segmentation_cost_type;
  _segmentation_cost_type segmentation_cost;

   typedef double _heading_cost_type;
  _heading_cost_type heading_cost;

   typedef double _speed_cost_type;
  _speed_cost_type speed_cost;

   typedef double _deviation_cost_type;
  _deviation_cost_type deviation_cost;





  typedef boost::shared_ptr< ::avt_341_msgs::DwaObjective_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::avt_341_msgs::DwaObjective_<ContainerAllocator> const> ConstPtr;

}; // struct DwaObjective_

typedef ::avt_341_msgs::DwaObjective_<std::allocator<void> > DwaObjective;

typedef boost::shared_ptr< ::avt_341_msgs::DwaObjective > DwaObjectivePtr;
typedef boost::shared_ptr< ::avt_341_msgs::DwaObjective const> DwaObjectiveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::avt_341_msgs::DwaObjective_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::avt_341_msgs::DwaObjective_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::avt_341_msgs::DwaObjective_<ContainerAllocator1> & lhs, const ::avt_341_msgs::DwaObjective_<ContainerAllocator2> & rhs)
{
  return lhs.goal_cost == rhs.goal_cost &&
    lhs.obstacle_cost == rhs.obstacle_cost &&
    lhs.segmentation_cost == rhs.segmentation_cost &&
    lhs.heading_cost == rhs.heading_cost &&
    lhs.speed_cost == rhs.speed_cost &&
    lhs.deviation_cost == rhs.deviation_cost;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::avt_341_msgs::DwaObjective_<ContainerAllocator1> & lhs, const ::avt_341_msgs::DwaObjective_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace avt_341_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::avt_341_msgs::DwaObjective_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::avt_341_msgs::DwaObjective_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::avt_341_msgs::DwaObjective_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::avt_341_msgs::DwaObjective_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avt_341_msgs::DwaObjective_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avt_341_msgs::DwaObjective_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::avt_341_msgs::DwaObjective_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0c23918921b89b7797bde9cc90d54688";
  }

  static const char* value(const ::avt_341_msgs::DwaObjective_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0c23918921b89b77ULL;
  static const uint64_t static_value2 = 0x97bde9cc90d54688ULL;
};

template<class ContainerAllocator>
struct DataType< ::avt_341_msgs::DwaObjective_<ContainerAllocator> >
{
  static const char* value()
  {
    return "avt_341_msgs/DwaObjective";
  }

  static const char* value(const ::avt_341_msgs::DwaObjective_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::avt_341_msgs::DwaObjective_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message contains the individual objective function cost terms values for\n"
"# a trajectory planned by the Dynamic Window Approach (DWA) planner. All cost\n"
"# terms in this message are already scaled by the user-defined weight factors.\n"
"\n"
"# Goal progress cost term.\n"
"float64 goal_cost\n"
"\n"
"# Obstacle avoidance cost term.\n"
"float64 obstacle_cost\n"
"\n"
"# Segmentation grid cost term.\n"
"float64 segmentation_cost\n"
"\n"
"# Heading deviation cost term.\n"
"float64 heading_cost\n"
"\n"
"# Target speed deviation cost term.\n"
"float64 speed_cost\n"
"\n"
"# Current trajectory deviation cost term.\n"
"float64 deviation_cost\n"
;
  }

  static const char* value(const ::avt_341_msgs::DwaObjective_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::avt_341_msgs::DwaObjective_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_cost);
      stream.next(m.obstacle_cost);
      stream.next(m.segmentation_cost);
      stream.next(m.heading_cost);
      stream.next(m.speed_cost);
      stream.next(m.deviation_cost);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DwaObjective_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::avt_341_msgs::DwaObjective_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::avt_341_msgs::DwaObjective_<ContainerAllocator>& v)
  {
    s << indent << "goal_cost: ";
    Printer<double>::stream(s, indent + "  ", v.goal_cost);
    s << indent << "obstacle_cost: ";
    Printer<double>::stream(s, indent + "  ", v.obstacle_cost);
    s << indent << "segmentation_cost: ";
    Printer<double>::stream(s, indent + "  ", v.segmentation_cost);
    s << indent << "heading_cost: ";
    Printer<double>::stream(s, indent + "  ", v.heading_cost);
    s << indent << "speed_cost: ";
    Printer<double>::stream(s, indent + "  ", v.speed_cost);
    s << indent << "deviation_cost: ";
    Printer<double>::stream(s, indent + "  ", v.deviation_cost);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AVT_341_MSGS_MESSAGE_DWAOBJECTIVE_H
