// Generated by gencpp from file avt_341_msgs/DwaTrajectory.msg
// DO NOT EDIT!


#ifndef AVT_341_MSGS_MESSAGE_DWATRAJECTORY_H
#define AVT_341_MSGS_MESSAGE_DWATRAJECTORY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nav_msgs/Path.h>
#include <avt_341_msgs/DwaObjective.h>

namespace avt_341_msgs
{
template <class ContainerAllocator>
struct DwaTrajectory_
{
  typedef DwaTrajectory_<ContainerAllocator> Type;

  DwaTrajectory_()
    : path()
    , objective()
    , cost(0.0)  {
    }
  DwaTrajectory_(const ContainerAllocator& _alloc)
    : path(_alloc)
    , objective(_alloc)
    , cost(0.0)  {
  (void)_alloc;
    }



   typedef  ::nav_msgs::Path_<ContainerAllocator>  _path_type;
  _path_type path;

   typedef  ::avt_341_msgs::DwaObjective_<ContainerAllocator>  _objective_type;
  _objective_type objective;

   typedef double _cost_type;
  _cost_type cost;





  typedef boost::shared_ptr< ::avt_341_msgs::DwaTrajectory_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::avt_341_msgs::DwaTrajectory_<ContainerAllocator> const> ConstPtr;

}; // struct DwaTrajectory_

typedef ::avt_341_msgs::DwaTrajectory_<std::allocator<void> > DwaTrajectory;

typedef boost::shared_ptr< ::avt_341_msgs::DwaTrajectory > DwaTrajectoryPtr;
typedef boost::shared_ptr< ::avt_341_msgs::DwaTrajectory const> DwaTrajectoryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::avt_341_msgs::DwaTrajectory_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::avt_341_msgs::DwaTrajectory_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::avt_341_msgs::DwaTrajectory_<ContainerAllocator1> & lhs, const ::avt_341_msgs::DwaTrajectory_<ContainerAllocator2> & rhs)
{
  return lhs.path == rhs.path &&
    lhs.objective == rhs.objective &&
    lhs.cost == rhs.cost;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::avt_341_msgs::DwaTrajectory_<ContainerAllocator1> & lhs, const ::avt_341_msgs::DwaTrajectory_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace avt_341_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::avt_341_msgs::DwaTrajectory_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::avt_341_msgs::DwaTrajectory_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::avt_341_msgs::DwaTrajectory_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::avt_341_msgs::DwaTrajectory_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avt_341_msgs::DwaTrajectory_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avt_341_msgs::DwaTrajectory_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::avt_341_msgs::DwaTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "02949f28799d0ba3776b1635badb3cca";
  }

  static const char* value(const ::avt_341_msgs::DwaTrajectory_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x02949f28799d0ba3ULL;
  static const uint64_t static_value2 = 0x776b1635badb3ccaULL;
};

template<class ContainerAllocator>
struct DataType< ::avt_341_msgs::DwaTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "avt_341_msgs/DwaTrajectory";
  }

  static const char* value(const ::avt_341_msgs::DwaTrajectory_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::avt_341_msgs::DwaTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message contains information on a simulated trajectory generated and\n"
"# evaluated by the Dynamic Window Approach (DWA) planner.\n"
"\n"
"# Predicted path for the simulated trajectory. \n"
"nav_msgs/Path path\n"
"\n"
"# The individual cost term values for the objective function across the entire\n"
"# trajectory. The values contained in this field are already scaled by the planner\n"
"# weights.\n"
"DwaObjective objective\n"
"\n"
"# Cumulative cost for all objective function cost terms after scaling. This\n"
"# field is equivalent to the sum of all the individual terms contained in the\n"
"# objective function message. \n"
"float64 cost\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/Path\n"
"#An array of poses that represents a Path for a robot to follow\n"
"Header header\n"
"geometry_msgs/PoseStamped[] poses\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: avt_341_msgs/DwaObjective\n"
"# This message contains the individual objective function cost terms values for\n"
"# a trajectory planned by the Dynamic Window Approach (DWA) planner. All cost\n"
"# terms in this message are already scaled by the user-defined weight factors.\n"
"\n"
"# Goal progress cost term.\n"
"float64 goal_cost\n"
"\n"
"# Obstacle avoidance cost term.\n"
"float64 obstacle_cost\n"
"\n"
"# Segmentation grid cost term.\n"
"float64 segmentation_cost\n"
"\n"
"# Heading deviation cost term.\n"
"float64 heading_cost\n"
"\n"
"# Target speed deviation cost term.\n"
"float64 speed_cost\n"
"\n"
"# Current trajectory deviation cost term.\n"
"float64 deviation_cost\n"
;
  }

  static const char* value(const ::avt_341_msgs::DwaTrajectory_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::avt_341_msgs::DwaTrajectory_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path);
      stream.next(m.objective);
      stream.next(m.cost);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DwaTrajectory_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::avt_341_msgs::DwaTrajectory_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::avt_341_msgs::DwaTrajectory_<ContainerAllocator>& v)
  {
    s << indent << "path: ";
    s << std::endl;
    Printer< ::nav_msgs::Path_<ContainerAllocator> >::stream(s, indent + "  ", v.path);
    s << indent << "objective: ";
    s << std::endl;
    Printer< ::avt_341_msgs::DwaObjective_<ContainerAllocator> >::stream(s, indent + "  ", v.objective);
    s << indent << "cost: ";
    Printer<double>::stream(s, indent + "  ", v.cost);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AVT_341_MSGS_MESSAGE_DWATRAJECTORY_H
