// Generated by gencpp from file avt_341_msgs/FollowerStatus.msg
// DO NOT EDIT!


#ifndef AVT_341_MSGS_MESSAGE_FOLLOWERSTATUS_H
#define AVT_341_MSGS_MESSAGE_FOLLOWERSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace avt_341_msgs
{
template <class ContainerAllocator>
struct FollowerStatus_
{
  typedef FollowerStatus_<ContainerAllocator> Type;

  FollowerStatus_()
    : leader_name()
    , x_offset(0.0)
    , y_offset(0.0)
    , use_leader(false)  {
    }
  FollowerStatus_(const ContainerAllocator& _alloc)
    : leader_name(_alloc)
    , x_offset(0.0)
    , y_offset(0.0)
    , use_leader(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _leader_name_type;
  _leader_name_type leader_name;

   typedef double _x_offset_type;
  _x_offset_type x_offset;

   typedef double _y_offset_type;
  _y_offset_type y_offset;

   typedef uint8_t _use_leader_type;
  _use_leader_type use_leader;





  typedef boost::shared_ptr< ::avt_341_msgs::FollowerStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::avt_341_msgs::FollowerStatus_<ContainerAllocator> const> ConstPtr;

}; // struct FollowerStatus_

typedef ::avt_341_msgs::FollowerStatus_<std::allocator<void> > FollowerStatus;

typedef boost::shared_ptr< ::avt_341_msgs::FollowerStatus > FollowerStatusPtr;
typedef boost::shared_ptr< ::avt_341_msgs::FollowerStatus const> FollowerStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::avt_341_msgs::FollowerStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::avt_341_msgs::FollowerStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::avt_341_msgs::FollowerStatus_<ContainerAllocator1> & lhs, const ::avt_341_msgs::FollowerStatus_<ContainerAllocator2> & rhs)
{
  return lhs.leader_name == rhs.leader_name &&
    lhs.x_offset == rhs.x_offset &&
    lhs.y_offset == rhs.y_offset &&
    lhs.use_leader == rhs.use_leader;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::avt_341_msgs::FollowerStatus_<ContainerAllocator1> & lhs, const ::avt_341_msgs::FollowerStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace avt_341_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::avt_341_msgs::FollowerStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::avt_341_msgs::FollowerStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::avt_341_msgs::FollowerStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::avt_341_msgs::FollowerStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avt_341_msgs::FollowerStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avt_341_msgs::FollowerStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::avt_341_msgs::FollowerStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "61986abde49829e549c712689cef646e";
  }

  static const char* value(const ::avt_341_msgs::FollowerStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x61986abde49829e5ULL;
  static const uint64_t static_value2 = 0x49c712689cef646eULL;
};

template<class ContainerAllocator>
struct DataType< ::avt_341_msgs::FollowerStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "avt_341_msgs/FollowerStatus";
  }

  static const char* value(const ::avt_341_msgs::FollowerStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::avt_341_msgs::FollowerStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string leader_name\n"
"float64 x_offset\n"
"float64 y_offset\n"
"bool use_leader\n"
;
  }

  static const char* value(const ::avt_341_msgs::FollowerStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::avt_341_msgs::FollowerStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.leader_name);
      stream.next(m.x_offset);
      stream.next(m.y_offset);
      stream.next(m.use_leader);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FollowerStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::avt_341_msgs::FollowerStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::avt_341_msgs::FollowerStatus_<ContainerAllocator>& v)
  {
    s << indent << "leader_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.leader_name);
    s << indent << "x_offset: ";
    Printer<double>::stream(s, indent + "  ", v.x_offset);
    s << indent << "y_offset: ";
    Printer<double>::stream(s, indent + "  ", v.y_offset);
    s << indent << "use_leader: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.use_leader);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AVT_341_MSGS_MESSAGE_FOLLOWERSTATUS_H
