// Generated by gencpp from file avt_341_msgs/Hypothesis.msg
// DO NOT EDIT!


#ifndef AVT_341_MSGS_MESSAGE_HYPOTHESIS_H
#define AVT_341_MSGS_MESSAGE_HYPOTHESIS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace avt_341_msgs
{
template <class ContainerAllocator>
struct Hypothesis_
{
  typedef Hypothesis_<ContainerAllocator> Type;

  Hypothesis_()
    : id(0)
    , label()
    , score(0.0)  {
    }
  Hypothesis_(const ContainerAllocator& _alloc)
    : id(0)
    , label(_alloc)
    , score(0.0)  {
  (void)_alloc;
    }



   typedef int16_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _label_type;
  _label_type label;

   typedef double _score_type;
  _score_type score;





  typedef boost::shared_ptr< ::avt_341_msgs::Hypothesis_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::avt_341_msgs::Hypothesis_<ContainerAllocator> const> ConstPtr;

}; // struct Hypothesis_

typedef ::avt_341_msgs::Hypothesis_<std::allocator<void> > Hypothesis;

typedef boost::shared_ptr< ::avt_341_msgs::Hypothesis > HypothesisPtr;
typedef boost::shared_ptr< ::avt_341_msgs::Hypothesis const> HypothesisConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::avt_341_msgs::Hypothesis_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::avt_341_msgs::Hypothesis_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::avt_341_msgs::Hypothesis_<ContainerAllocator1> & lhs, const ::avt_341_msgs::Hypothesis_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.label == rhs.label &&
    lhs.score == rhs.score;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::avt_341_msgs::Hypothesis_<ContainerAllocator1> & lhs, const ::avt_341_msgs::Hypothesis_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace avt_341_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::avt_341_msgs::Hypothesis_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::avt_341_msgs::Hypothesis_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::avt_341_msgs::Hypothesis_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::avt_341_msgs::Hypothesis_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avt_341_msgs::Hypothesis_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avt_341_msgs::Hypothesis_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::avt_341_msgs::Hypothesis_<ContainerAllocator> >
{
  static const char* value()
  {
    return "881cf7be7c3682970b3b9514be4103fc";
  }

  static const char* value(const ::avt_341_msgs::Hypothesis_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x881cf7be7c368297ULL;
  static const uint64_t static_value2 = 0x0b3b9514be4103fcULL;
};

template<class ContainerAllocator>
struct DataType< ::avt_341_msgs::Hypothesis_<ContainerAllocator> >
{
  static const char* value()
  {
    return "avt_341_msgs/Hypothesis";
  }

  static const char* value(const ::avt_341_msgs::Hypothesis_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::avt_341_msgs::Hypothesis_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message represents an object hypothesis formulated by an object detector\n"
"# for a given region of the image.\n"
"\n"
"# The unique identifier of the object class as specified by the object detector.\n"
"int16 id\n"
"\n"
"# The human-readable label of the object class as specified by the object\n"
"# detector.\n"
"string label\n"
"\n"
"# The score associated with the hypothesis, as a floating point number between\n"
"# 0.0 and 1.0, including the limits.\n"
"float64 score\n"
;
  }

  static const char* value(const ::avt_341_msgs::Hypothesis_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::avt_341_msgs::Hypothesis_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.label);
      stream.next(m.score);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Hypothesis_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::avt_341_msgs::Hypothesis_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::avt_341_msgs::Hypothesis_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.id);
    s << indent << "label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.label);
    s << indent << "score: ";
    Printer<double>::stream(s, indent + "  ", v.score);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AVT_341_MSGS_MESSAGE_HYPOTHESIS_H
