// Generated by gencpp from file avt_341_msgs/LiorfCloudInfo.msg
// DO NOT EDIT!


#ifndef AVT_341_MSGS_MESSAGE_LIORFCLOUDINFO_H
#define AVT_341_MSGS_MESSAGE_LIORFCLOUDINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sensor_msgs/PointCloud2.h>
#include <sensor_msgs/PointCloud2.h>
#include <sensor_msgs/PointCloud2.h>
#include <sensor_msgs/PointCloud2.h>
#include <sensor_msgs/PointCloud2.h>
#include <sensor_msgs/PointCloud2.h>
#include <sensor_msgs/PointCloud2.h>

namespace avt_341_msgs
{
template <class ContainerAllocator>
struct LiorfCloudInfo_
{
  typedef LiorfCloudInfo_<ContainerAllocator> Type;

  LiorfCloudInfo_()
    : header()
    , start_ring_index()
    , end_ring_index()
    , point_col_ind()
    , point_range()
    , imu_available(0)
    , odom_available(0)
    , imu_roll_init(0.0)
    , imu_pitch_init(0.0)
    , imu_yaw_init(0.0)
    , initial_guess_x(0.0)
    , initial_guess_y(0.0)
    , initial_guess_z(0.0)
    , initial_guess_roll(0.0)
    , initial_guess_pitch(0.0)
    , initial_guess_yaw(0.0)
    , cloud_deskewed()
    , cloud_corner()
    , cloud_surface()
    , key_frame_cloud()
    , key_frame_color()
    , key_frame_poses()
    , key_frame_map()  {
    }
  LiorfCloudInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , start_ring_index(_alloc)
    , end_ring_index(_alloc)
    , point_col_ind(_alloc)
    , point_range(_alloc)
    , imu_available(0)
    , odom_available(0)
    , imu_roll_init(0.0)
    , imu_pitch_init(0.0)
    , imu_yaw_init(0.0)
    , initial_guess_x(0.0)
    , initial_guess_y(0.0)
    , initial_guess_z(0.0)
    , initial_guess_roll(0.0)
    , initial_guess_pitch(0.0)
    , initial_guess_yaw(0.0)
    , cloud_deskewed(_alloc)
    , cloud_corner(_alloc)
    , cloud_surface(_alloc)
    , key_frame_cloud(_alloc)
    , key_frame_color(_alloc)
    , key_frame_poses(_alloc)
    , key_frame_map(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _start_ring_index_type;
  _start_ring_index_type start_ring_index;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _end_ring_index_type;
  _end_ring_index_type end_ring_index;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _point_col_ind_type;
  _point_col_ind_type point_col_ind;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _point_range_type;
  _point_range_type point_range;

   typedef int64_t _imu_available_type;
  _imu_available_type imu_available;

   typedef int64_t _odom_available_type;
  _odom_available_type odom_available;

   typedef float _imu_roll_init_type;
  _imu_roll_init_type imu_roll_init;

   typedef float _imu_pitch_init_type;
  _imu_pitch_init_type imu_pitch_init;

   typedef float _imu_yaw_init_type;
  _imu_yaw_init_type imu_yaw_init;

   typedef float _initial_guess_x_type;
  _initial_guess_x_type initial_guess_x;

   typedef float _initial_guess_y_type;
  _initial_guess_y_type initial_guess_y;

   typedef float _initial_guess_z_type;
  _initial_guess_z_type initial_guess_z;

   typedef float _initial_guess_roll_type;
  _initial_guess_roll_type initial_guess_roll;

   typedef float _initial_guess_pitch_type;
  _initial_guess_pitch_type initial_guess_pitch;

   typedef float _initial_guess_yaw_type;
  _initial_guess_yaw_type initial_guess_yaw;

   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _cloud_deskewed_type;
  _cloud_deskewed_type cloud_deskewed;

   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _cloud_corner_type;
  _cloud_corner_type cloud_corner;

   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _cloud_surface_type;
  _cloud_surface_type cloud_surface;

   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _key_frame_cloud_type;
  _key_frame_cloud_type key_frame_cloud;

   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _key_frame_color_type;
  _key_frame_color_type key_frame_color;

   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _key_frame_poses_type;
  _key_frame_poses_type key_frame_poses;

   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _key_frame_map_type;
  _key_frame_map_type key_frame_map;





  typedef boost::shared_ptr< ::avt_341_msgs::LiorfCloudInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::avt_341_msgs::LiorfCloudInfo_<ContainerAllocator> const> ConstPtr;

}; // struct LiorfCloudInfo_

typedef ::avt_341_msgs::LiorfCloudInfo_<std::allocator<void> > LiorfCloudInfo;

typedef boost::shared_ptr< ::avt_341_msgs::LiorfCloudInfo > LiorfCloudInfoPtr;
typedef boost::shared_ptr< ::avt_341_msgs::LiorfCloudInfo const> LiorfCloudInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::avt_341_msgs::LiorfCloudInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::avt_341_msgs::LiorfCloudInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::avt_341_msgs::LiorfCloudInfo_<ContainerAllocator1> & lhs, const ::avt_341_msgs::LiorfCloudInfo_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.start_ring_index == rhs.start_ring_index &&
    lhs.end_ring_index == rhs.end_ring_index &&
    lhs.point_col_ind == rhs.point_col_ind &&
    lhs.point_range == rhs.point_range &&
    lhs.imu_available == rhs.imu_available &&
    lhs.odom_available == rhs.odom_available &&
    lhs.imu_roll_init == rhs.imu_roll_init &&
    lhs.imu_pitch_init == rhs.imu_pitch_init &&
    lhs.imu_yaw_init == rhs.imu_yaw_init &&
    lhs.initial_guess_x == rhs.initial_guess_x &&
    lhs.initial_guess_y == rhs.initial_guess_y &&
    lhs.initial_guess_z == rhs.initial_guess_z &&
    lhs.initial_guess_roll == rhs.initial_guess_roll &&
    lhs.initial_guess_pitch == rhs.initial_guess_pitch &&
    lhs.initial_guess_yaw == rhs.initial_guess_yaw &&
    lhs.cloud_deskewed == rhs.cloud_deskewed &&
    lhs.cloud_corner == rhs.cloud_corner &&
    lhs.cloud_surface == rhs.cloud_surface &&
    lhs.key_frame_cloud == rhs.key_frame_cloud &&
    lhs.key_frame_color == rhs.key_frame_color &&
    lhs.key_frame_poses == rhs.key_frame_poses &&
    lhs.key_frame_map == rhs.key_frame_map;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::avt_341_msgs::LiorfCloudInfo_<ContainerAllocator1> & lhs, const ::avt_341_msgs::LiorfCloudInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace avt_341_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::avt_341_msgs::LiorfCloudInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::avt_341_msgs::LiorfCloudInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::avt_341_msgs::LiorfCloudInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::avt_341_msgs::LiorfCloudInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avt_341_msgs::LiorfCloudInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avt_341_msgs::LiorfCloudInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::avt_341_msgs::LiorfCloudInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "77d1090deb18ae73b305d35de4ac9b40";
  }

  static const char* value(const ::avt_341_msgs::LiorfCloudInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x77d1090deb18ae73ULL;
  static const uint64_t static_value2 = 0xb305d35de4ac9b40ULL;
};

template<class ContainerAllocator>
struct DataType< ::avt_341_msgs::LiorfCloudInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "avt_341_msgs/LiorfCloudInfo";
  }

  static const char* value(const ::avt_341_msgs::LiorfCloudInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::avt_341_msgs::LiorfCloudInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Cloud Info\n"
"std_msgs/Header header \n"
"\n"
"int32[] start_ring_index\n"
"int32[] end_ring_index\n"
"\n"
"int32[]  point_col_ind # point column index in range image\n"
"float32[] point_range # point range \n"
"\n"
"int64 imu_available\n"
"int64 odom_available\n"
"\n"
"# Attitude for LOAM initialization\n"
"float32 imu_roll_init\n"
"float32 imu_pitch_init\n"
"float32 imu_yaw_init\n"
"\n"
"# Initial guess from imu pre-integration\n"
"float32 initial_guess_x\n"
"float32 initial_guess_y\n"
"float32 initial_guess_z\n"
"float32 initial_guess_roll\n"
"float32 initial_guess_pitch\n"
"float32 initial_guess_yaw\n"
"\n"
"# Point cloud messages\n"
"sensor_msgs/PointCloud2 cloud_deskewed  # original cloud deskewed\n"
"sensor_msgs/PointCloud2 cloud_corner    # extracted corner feature\n"
"sensor_msgs/PointCloud2 cloud_surface   # extracted surface feature\n"
"\n"
"# 3rd party messages\n"
"sensor_msgs/PointCloud2 key_frame_cloud\n"
"sensor_msgs/PointCloud2 key_frame_color\n"
"sensor_msgs/PointCloud2 key_frame_poses\n"
"sensor_msgs/PointCloud2 key_frame_map\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointCloud2\n"
"# This message holds a collection of N-dimensional points, which may\n"
"# contain additional information such as normals, intensity, etc. The\n"
"# point data is stored as a binary blob, its layout described by the\n"
"# contents of the \"fields\" array.\n"
"\n"
"# The point cloud data may be organized 2d (image-like) or 1d\n"
"# (unordered). Point clouds organized as 2d images may be produced by\n"
"# camera depth sensors such as stereo or time-of-flight.\n"
"\n"
"# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n"
"# points).\n"
"Header header\n"
"\n"
"# 2D structure of the point cloud. If the cloud is unordered, height is\n"
"# 1 and width is the length of the point cloud.\n"
"uint32 height\n"
"uint32 width\n"
"\n"
"# Describes the channels and their layout in the binary data blob.\n"
"PointField[] fields\n"
"\n"
"bool    is_bigendian # Is this data bigendian?\n"
"uint32  point_step   # Length of a point in bytes\n"
"uint32  row_step     # Length of a row in bytes\n"
"uint8[] data         # Actual point data, size is (row_step*height)\n"
"\n"
"bool is_dense        # True if there are no invalid points\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointField\n"
"# This message holds the description of one point entry in the\n"
"# PointCloud2 message format.\n"
"uint8 INT8    = 1\n"
"uint8 UINT8   = 2\n"
"uint8 INT16   = 3\n"
"uint8 UINT16  = 4\n"
"uint8 INT32   = 5\n"
"uint8 UINT32  = 6\n"
"uint8 FLOAT32 = 7\n"
"uint8 FLOAT64 = 8\n"
"\n"
"string name      # Name of field\n"
"uint32 offset    # Offset from start of point struct\n"
"uint8  datatype  # Datatype enumeration, see above\n"
"uint32 count     # How many elements in the field\n"
;
  }

  static const char* value(const ::avt_341_msgs::LiorfCloudInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::avt_341_msgs::LiorfCloudInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.start_ring_index);
      stream.next(m.end_ring_index);
      stream.next(m.point_col_ind);
      stream.next(m.point_range);
      stream.next(m.imu_available);
      stream.next(m.odom_available);
      stream.next(m.imu_roll_init);
      stream.next(m.imu_pitch_init);
      stream.next(m.imu_yaw_init);
      stream.next(m.initial_guess_x);
      stream.next(m.initial_guess_y);
      stream.next(m.initial_guess_z);
      stream.next(m.initial_guess_roll);
      stream.next(m.initial_guess_pitch);
      stream.next(m.initial_guess_yaw);
      stream.next(m.cloud_deskewed);
      stream.next(m.cloud_corner);
      stream.next(m.cloud_surface);
      stream.next(m.key_frame_cloud);
      stream.next(m.key_frame_color);
      stream.next(m.key_frame_poses);
      stream.next(m.key_frame_map);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LiorfCloudInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::avt_341_msgs::LiorfCloudInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::avt_341_msgs::LiorfCloudInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "start_ring_index[]" << std::endl;
    for (size_t i = 0; i < v.start_ring_index.size(); ++i)
    {
      s << indent << "  start_ring_index[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.start_ring_index[i]);
    }
    s << indent << "end_ring_index[]" << std::endl;
    for (size_t i = 0; i < v.end_ring_index.size(); ++i)
    {
      s << indent << "  end_ring_index[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.end_ring_index[i]);
    }
    s << indent << "point_col_ind[]" << std::endl;
    for (size_t i = 0; i < v.point_col_ind.size(); ++i)
    {
      s << indent << "  point_col_ind[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.point_col_ind[i]);
    }
    s << indent << "point_range[]" << std::endl;
    for (size_t i = 0; i < v.point_range.size(); ++i)
    {
      s << indent << "  point_range[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.point_range[i]);
    }
    s << indent << "imu_available: ";
    Printer<int64_t>::stream(s, indent + "  ", v.imu_available);
    s << indent << "odom_available: ";
    Printer<int64_t>::stream(s, indent + "  ", v.odom_available);
    s << indent << "imu_roll_init: ";
    Printer<float>::stream(s, indent + "  ", v.imu_roll_init);
    s << indent << "imu_pitch_init: ";
    Printer<float>::stream(s, indent + "  ", v.imu_pitch_init);
    s << indent << "imu_yaw_init: ";
    Printer<float>::stream(s, indent + "  ", v.imu_yaw_init);
    s << indent << "initial_guess_x: ";
    Printer<float>::stream(s, indent + "  ", v.initial_guess_x);
    s << indent << "initial_guess_y: ";
    Printer<float>::stream(s, indent + "  ", v.initial_guess_y);
    s << indent << "initial_guess_z: ";
    Printer<float>::stream(s, indent + "  ", v.initial_guess_z);
    s << indent << "initial_guess_roll: ";
    Printer<float>::stream(s, indent + "  ", v.initial_guess_roll);
    s << indent << "initial_guess_pitch: ";
    Printer<float>::stream(s, indent + "  ", v.initial_guess_pitch);
    s << indent << "initial_guess_yaw: ";
    Printer<float>::stream(s, indent + "  ", v.initial_guess_yaw);
    s << indent << "cloud_deskewed: ";
    s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.cloud_deskewed);
    s << indent << "cloud_corner: ";
    s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.cloud_corner);
    s << indent << "cloud_surface: ";
    s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.cloud_surface);
    s << indent << "key_frame_cloud: ";
    s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.key_frame_cloud);
    s << indent << "key_frame_color: ";
    s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.key_frame_color);
    s << indent << "key_frame_poses: ";
    s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.key_frame_poses);
    s << indent << "key_frame_map: ";
    s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.key_frame_map);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AVT_341_MSGS_MESSAGE_LIORFCLOUDINFO_H
