// Generated by gencpp from file avt_341_msgs/LiorfSaveMap.msg
// DO NOT EDIT!


#ifndef AVT_341_MSGS_MESSAGE_LIORFSAVEMAP_H
#define AVT_341_MSGS_MESSAGE_LIORFSAVEMAP_H

#include <ros/service_traits.h>


#include <avt_341_msgs/LiorfSaveMapRequest.h>
#include <avt_341_msgs/LiorfSaveMapResponse.h>


namespace avt_341_msgs
{

struct LiorfSaveMap
{

typedef LiorfSaveMapRequest Request;
typedef LiorfSaveMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LiorfSaveMap
} // namespace avt_341_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::avt_341_msgs::LiorfSaveMap > {
  static const char* value()
  {
    return "9b82c64d089149d300598523af304f22";
  }

  static const char* value(const ::avt_341_msgs::LiorfSaveMap&) { return value(); }
};

template<>
struct DataType< ::avt_341_msgs::LiorfSaveMap > {
  static const char* value()
  {
    return "avt_341_msgs/LiorfSaveMap";
  }

  static const char* value(const ::avt_341_msgs::LiorfSaveMap&) { return value(); }
};


// service_traits::MD5Sum< ::avt_341_msgs::LiorfSaveMapRequest> should match
// service_traits::MD5Sum< ::avt_341_msgs::LiorfSaveMap >
template<>
struct MD5Sum< ::avt_341_msgs::LiorfSaveMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::avt_341_msgs::LiorfSaveMap >::value();
  }
  static const char* value(const ::avt_341_msgs::LiorfSaveMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::avt_341_msgs::LiorfSaveMapRequest> should match
// service_traits::DataType< ::avt_341_msgs::LiorfSaveMap >
template<>
struct DataType< ::avt_341_msgs::LiorfSaveMapRequest>
{
  static const char* value()
  {
    return DataType< ::avt_341_msgs::LiorfSaveMap >::value();
  }
  static const char* value(const ::avt_341_msgs::LiorfSaveMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::avt_341_msgs::LiorfSaveMapResponse> should match
// service_traits::MD5Sum< ::avt_341_msgs::LiorfSaveMap >
template<>
struct MD5Sum< ::avt_341_msgs::LiorfSaveMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::avt_341_msgs::LiorfSaveMap >::value();
  }
  static const char* value(const ::avt_341_msgs::LiorfSaveMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::avt_341_msgs::LiorfSaveMapResponse> should match
// service_traits::DataType< ::avt_341_msgs::LiorfSaveMap >
template<>
struct DataType< ::avt_341_msgs::LiorfSaveMapResponse>
{
  static const char* value()
  {
    return DataType< ::avt_341_msgs::LiorfSaveMap >::value();
  }
  static const char* value(const ::avt_341_msgs::LiorfSaveMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AVT_341_MSGS_MESSAGE_LIORFSAVEMAP_H
