// Generated by gencpp from file avt_341_msgs/LiorfSaveMapRequest.msg
// DO NOT EDIT!


#ifndef AVT_341_MSGS_MESSAGE_LIORFSAVEMAPREQUEST_H
#define AVT_341_MSGS_MESSAGE_LIORFSAVEMAPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace avt_341_msgs
{
template <class ContainerAllocator>
struct LiorfSaveMapRequest_
{
  typedef LiorfSaveMapRequest_<ContainerAllocator> Type;

  LiorfSaveMapRequest_()
    : resolution(0.0)
    , destination()  {
    }
  LiorfSaveMapRequest_(const ContainerAllocator& _alloc)
    : resolution(0.0)
    , destination(_alloc)  {
  (void)_alloc;
    }



   typedef float _resolution_type;
  _resolution_type resolution;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _destination_type;
  _destination_type destination;





  typedef boost::shared_ptr< ::avt_341_msgs::LiorfSaveMapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::avt_341_msgs::LiorfSaveMapRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LiorfSaveMapRequest_

typedef ::avt_341_msgs::LiorfSaveMapRequest_<std::allocator<void> > LiorfSaveMapRequest;

typedef boost::shared_ptr< ::avt_341_msgs::LiorfSaveMapRequest > LiorfSaveMapRequestPtr;
typedef boost::shared_ptr< ::avt_341_msgs::LiorfSaveMapRequest const> LiorfSaveMapRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::avt_341_msgs::LiorfSaveMapRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::avt_341_msgs::LiorfSaveMapRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::avt_341_msgs::LiorfSaveMapRequest_<ContainerAllocator1> & lhs, const ::avt_341_msgs::LiorfSaveMapRequest_<ContainerAllocator2> & rhs)
{
  return lhs.resolution == rhs.resolution &&
    lhs.destination == rhs.destination;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::avt_341_msgs::LiorfSaveMapRequest_<ContainerAllocator1> & lhs, const ::avt_341_msgs::LiorfSaveMapRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace avt_341_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::avt_341_msgs::LiorfSaveMapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::avt_341_msgs::LiorfSaveMapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::avt_341_msgs::LiorfSaveMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::avt_341_msgs::LiorfSaveMapRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avt_341_msgs::LiorfSaveMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avt_341_msgs::LiorfSaveMapRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::avt_341_msgs::LiorfSaveMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8129166042856bf2b765173d013957f2";
  }

  static const char* value(const ::avt_341_msgs::LiorfSaveMapRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8129166042856bf2ULL;
  static const uint64_t static_value2 = 0xb765173d013957f2ULL;
};

template<class ContainerAllocator>
struct DataType< ::avt_341_msgs::LiorfSaveMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "avt_341_msgs/LiorfSaveMapRequest";
  }

  static const char* value(const ::avt_341_msgs::LiorfSaveMapRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::avt_341_msgs::LiorfSaveMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 resolution\n"
"string destination\n"
;
  }

  static const char* value(const ::avt_341_msgs::LiorfSaveMapRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::avt_341_msgs::LiorfSaveMapRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.resolution);
      stream.next(m.destination);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LiorfSaveMapRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::avt_341_msgs::LiorfSaveMapRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::avt_341_msgs::LiorfSaveMapRequest_<ContainerAllocator>& v)
  {
    s << indent << "resolution: ";
    Printer<float>::stream(s, indent + "  ", v.resolution);
    s << indent << "destination: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.destination);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AVT_341_MSGS_MESSAGE_LIORFSAVEMAPREQUEST_H
