// Generated by gencpp from file avt_341_msgs/OccupiedCells.msg
// DO NOT EDIT!


#ifndef AVT_341_MSGS_MESSAGE_OCCUPIEDCELLS_H
#define AVT_341_MSGS_MESSAGE_OCCUPIEDCELLS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <nav_msgs/MapMetaData.h>
#include <avt_341_msgs/OccupiedCell.h>

namespace avt_341_msgs
{
template <class ContainerAllocator>
struct OccupiedCells_
{
  typedef OccupiedCells_<ContainerAllocator> Type;

  OccupiedCells_()
    : header()
    , info()
    , cells()  {
    }
  OccupiedCells_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , info(_alloc)
    , cells(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::nav_msgs::MapMetaData_<ContainerAllocator>  _info_type;
  _info_type info;

   typedef std::vector< ::avt_341_msgs::OccupiedCell_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::avt_341_msgs::OccupiedCell_<ContainerAllocator> >> _cells_type;
  _cells_type cells;





  typedef boost::shared_ptr< ::avt_341_msgs::OccupiedCells_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::avt_341_msgs::OccupiedCells_<ContainerAllocator> const> ConstPtr;

}; // struct OccupiedCells_

typedef ::avt_341_msgs::OccupiedCells_<std::allocator<void> > OccupiedCells;

typedef boost::shared_ptr< ::avt_341_msgs::OccupiedCells > OccupiedCellsPtr;
typedef boost::shared_ptr< ::avt_341_msgs::OccupiedCells const> OccupiedCellsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::avt_341_msgs::OccupiedCells_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::avt_341_msgs::OccupiedCells_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::avt_341_msgs::OccupiedCells_<ContainerAllocator1> & lhs, const ::avt_341_msgs::OccupiedCells_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.info == rhs.info &&
    lhs.cells == rhs.cells;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::avt_341_msgs::OccupiedCells_<ContainerAllocator1> & lhs, const ::avt_341_msgs::OccupiedCells_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace avt_341_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::avt_341_msgs::OccupiedCells_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::avt_341_msgs::OccupiedCells_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::avt_341_msgs::OccupiedCells_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::avt_341_msgs::OccupiedCells_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avt_341_msgs::OccupiedCells_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::avt_341_msgs::OccupiedCells_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::avt_341_msgs::OccupiedCells_<ContainerAllocator> >
{
  static const char* value()
  {
    return "37ed2b2acb76839816aaa89a306fe0dc";
  }

  static const char* value(const ::avt_341_msgs::OccupiedCells_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x37ed2b2acb768398ULL;
  static const uint64_t static_value2 = 0x16aaa89a306fe0dcULL;
};

template<class ContainerAllocator>
struct DataType< ::avt_341_msgs::OccupiedCells_<ContainerAllocator> >
{
  static const char* value()
  {
    return "avt_341_msgs/OccupiedCells";
  }

  static const char* value(const ::avt_341_msgs::OccupiedCells_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::avt_341_msgs::OccupiedCells_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"nav_msgs/MapMetaData info\n"
"avt_341_msgs/OccupiedCell[] cells\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/MapMetaData\n"
"# This hold basic information about the characterists of the OccupancyGrid\n"
"\n"
"# The time at which the map was loaded\n"
"time map_load_time\n"
"# The map resolution [m/cell]\n"
"float32 resolution\n"
"# Map width [cells]\n"
"uint32 width\n"
"# Map height [cells]\n"
"uint32 height\n"
"# The origin of the map [m, m, rad].  This is the real-world pose of the\n"
"# cell (0,0) in the map.\n"
"geometry_msgs/Pose origin\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: avt_341_msgs/OccupiedCell\n"
"uint32 x_index\n"
"uint32 y_index\n"
"int8 data\n"
;
  }

  static const char* value(const ::avt_341_msgs::OccupiedCells_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::avt_341_msgs::OccupiedCells_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.info);
      stream.next(m.cells);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OccupiedCells_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::avt_341_msgs::OccupiedCells_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::avt_341_msgs::OccupiedCells_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "info: ";
    s << std::endl;
    Printer< ::nav_msgs::MapMetaData_<ContainerAllocator> >::stream(s, indent + "  ", v.info);
    s << indent << "cells[]" << std::endl;
    for (size_t i = 0; i < v.cells.size(); ++i)
    {
      s << indent << "  cells[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::avt_341_msgs::OccupiedCell_<ContainerAllocator> >::stream(s, indent + "    ", v.cells[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AVT_341_MSGS_MESSAGE_OCCUPIEDCELLS_H
