# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from avt_341_msgs/FollowerStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class FollowerStatus(genpy.Message):
  _md5sum = "61986abde49829e549c712689cef646e"
  _type = "avt_341_msgs/FollowerStatus"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string leader_name
float64 x_offset
float64 y_offset
bool use_leader
"""
  __slots__ = ['leader_name','x_offset','y_offset','use_leader']
  _slot_types = ['string','float64','float64','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       leader_name,x_offset,y_offset,use_leader

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FollowerStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.leader_name is None:
        self.leader_name = ''
      if self.x_offset is None:
        self.x_offset = 0.
      if self.y_offset is None:
        self.y_offset = 0.
      if self.use_leader is None:
        self.use_leader = False
    else:
      self.leader_name = ''
      self.x_offset = 0.
      self.y_offset = 0.
      self.use_leader = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.leader_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2dB().pack(_x.x_offset, _x.y_offset, _x.use_leader))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.leader_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.leader_name = str[start:end]
      _x = self
      start = end
      end += 17
      (_x.x_offset, _x.y_offset, _x.use_leader,) = _get_struct_2dB().unpack(str[start:end])
      self.use_leader = bool(self.use_leader)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.leader_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2dB().pack(_x.x_offset, _x.y_offset, _x.use_leader))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.leader_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.leader_name = str[start:end]
      _x = self
      start = end
      end += 17
      (_x.x_offset, _x.y_offset, _x.use_leader,) = _get_struct_2dB().unpack(str[start:end])
      self.use_leader = bool(self.use_leader)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2dB = None
def _get_struct_2dB():
    global _struct_2dB
    if _struct_2dB is None:
        _struct_2dB = struct.Struct("<2dB")
    return _struct_2dB
