# Occupancy grid
# ======================================================================================================================
use_elevation: False                      # To use elevation or slope value when making occupancy grid based on heightmap.
slope_threshold: 0.5                      # Threshold within which next waypoint selected.
grid_height: 200.0                        # Grid height.
grid_width: 200.0                         # Grid width.
grid_llx: -100.0                           # X coordinate grid bottom left anchor point.
grid_lly: -100.0                           # Y coordinate grid bottom left anchor point.
grid_res: 0.5                             # Grid resolution in meters.
overhead_clearance: 7.0                   # Overhead clearance from vehicle after which lidar points ignored
grid_dilate: False                        # Whether or not to apply dilation.
grid_dilate_x: 2.0                        # Amount of dilation in x.
grid_dilate_y: 2.0                        # Amount of dilation in y.
grid_dilate_proportion: 0.8               # Proportion of original grid cell to dilate with.
cull_lidar: False                         # Cull lidar points flag based on distance from odometry.
cull_lidar_dist: 90.0                     # Maximum distance used to cull lidar points
cull_lidar_dist_min: 0.0                  # Minimum distance used to cull lidar points
warmup_time: 5.0                          # Time before lidar processing starts
stitch_lidar_points: True                 # If true, lidar scans will be stitched together. Else, each point cloud 2 message will be independent and the grid will be cleared between messages.
filter_highest_lidar: False               # If true, the highest point in each cell will be ignored and the second highest will be used for the slope calculations. If false, the highest point will be used.
time_register_window: 0.05                # Maximum window of time between odom and point cloud time stamps
perception_rate: 20.0                     # Publish rate for perception node

# Clearing method
# ======================================================================================================================
clear_method:
  type: 'none'                            # Costmap clearing method. none | time | raytrace | raytrace_obs_filter | no_obs_time.
  visualize: False                        # If true, visualizes costmap clearing method.
  visualize_range: 40.0                   # Visualization range for clear method debugging. If < 0 range limit is ignored and all cells are displayed.
  raytrace_range: 50.0                    # Maximum range for raytrace clearing.
  use_voxels: True                        # Maximum range for raytrace clearing.
  voxel_height_min: 0.0                   # Voxel grid height min used in raytrace_voxel clearing method.
  voxel_height_res: 0.5                   # Voxel grid height resolution used in raytrace_voxel clearing method.
  immediate_clear_dilation: True          # If true, dilation will be immediately cleared with cleared cells. If False, dilation will only be removed when dilated cell scanned and re-adjusts its height values.
  obs_filter_range: 1.0                   # Minimum distance from obstacles for clearing to occur. Only used with raytrace_obs_filter option.
  max_point_age: 5.0                      # Lifetime of a point before it is cleared when clear_method_type = time or no_obs_time set.
  sampled_threshold: 5                    # Minimum samples before cell cleared when clear_method_type=no_obs_time set.

# Segmentation
# ======================================================================================================================
global_grid_csv_path: "$Python:os.path.join(get_package_share_directory('avt_341'), 'config', '20230816_KRC_CP06_Scaled_FlippedVertical.csv')"      # Path to CSV containing KRC global segmentation grid.


# Lidar Obstacle Detector
# ======================================================================================================================
use_lidar_obstacle_detector: False      # If true uses lidar obstacle detector. ROS1 version only currently.
raw_points_topic: '/avt_341/points'         # The name of the points topic listened to by the obstacle detection node.
perception_points_topic: '/avt_341/points'  # The name of the points topic listened to by the perception node.