grid_width: 100.0
grid_height: 100.0
grid_llx: 0.0
grid_lly: 0.0
grid_res: 1.0
max_width: 100.0
max_height: 100.0
publish_uab_occupancy_grid: False
lidar_frame_id: "lidar"
odom_frame_id: "base_link"
camera_frame_id: "front_camera"
brightness_offset: 75.0
publish_window: False
debug_vis_segmentation: False