use_pca_box: false
use_tracking: true

voxel_grid_size: 0.2

roi_max_x: 70.0
roi_max_y: 30.0
roi_max_z: 3.0

roi_min_x: -5.0
roi_min_y: -30.0
roi_min_z: -2.5

body_max_x: 0.3
body_max_y: 0.8
body_max_z: 2.0

body_min_x: -2.2
body_min_y: -0.8
body_min_z: -0.3

ground_threshold: 0.3

cluster_threshold: 0.6
cluster_max_size: 5000
cluster_min_size: 10

displacement_threshold: 1.0
iou_threshold: 1.0

ground_normal_x: 0.0
ground_normal_y: 0.0
ground_normal_z: 1.0
ground_normal_threshold: 0.4

obstacle_scale: 1.0
obstacle_min_neighbors: 10