<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>avt_341_param_lib</name>
  <version>0.7.0</version>
  <description>Parameter library for ROS2 AVT-341/408.</description>
  <maintainer email="stefan.wapnick@nrc-cnrc.gc.ca">Stefan Wapnick</maintainer>
  <license>BSD-3-Clause</license>
  <author email="stefan.wapnick@nrc-cnrc.gc.ca">Stefan Wapnick</author>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <depend>python3</depend>
  <depend>python3-jinja2</depend>
  <depend>python3-typeguard</depend>
  <depend>python3-yaml</depend>

  <depend>fmt</depend>
  <depend>rclcpp</depend>
  <depend>rclpy</depend>
  <depend>rclcpp_lifecycle</depend>

  <test_depend>ament_cmake_pytest</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
