(cl:in-package avt_341_msgs-msg)
(cl:export '(SENDER_NAME-VAL
          SENDER_NAME
          MSG_ID-VAL
          MSG_ID
          TYPE-VAL
          TYPE
          FORMATION-VAL
          FORMATION
          RECEIVER_NAME-VAL
          RECEIVER_NAME
          LEADER_NAME-VAL
          LEADER_NAME
          FOLLOWER1_NAME-VAL
          FOLLOWER1_NAME
          FOLLOWER2_NAME-VAL
          FOLLOWER2_NAME
          FOLLOWER3_NAME-VAL
          FOLLOWER3_NAME
          OBJECTIVE_NAME-VAL
          OBJECTIVE_NAME
          DESIRED_SPEED-VAL
          DESIRED_SPEED
          PRIORITY_TYPE-VAL
          PRIORITY_TYPE
          TERMINATION_METHOD-VAL
          TERMINATION_METHOD
          X_SCALE-VAL
          X_SCALE
          Y_SCALE-VAL
          Y_SCALE
          X_OFFSET-VAL
          X_OFFSET
          Y_OFFSET-VAL
          Y_OFFSET
          DISTANCE-VAL
          DISTANCE
          TARGET_MSG_ID-VAL
          TARGET_MSG_ID
))