(cl:in-package avt_341_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          START_RING_INDEX-VAL
          START_RING_INDEX
          END_RING_INDEX-VAL
          END_RING_INDEX
          POINT_COL_IND-VAL
          POINT_COL_IND
          POINT_RANGE-VAL
          POINT_RANGE
          IMU_AVAILABLE-VAL
          IMU_AVAILABLE
          ODOM_AVAILABLE-VAL
          ODOM_AVAILABLE
          IMU_ROLL_INIT-VAL
          IMU_ROLL_INIT
          IMU_PITCH_INIT-VAL
          IMU_PITCH_INIT
          IMU_YAW_INIT-VAL
          IMU_YAW_INIT
          INITIAL_GUESS_X-VAL
          INITIAL_GUESS_X
          INITIAL_GUESS_Y-VAL
          INITIAL_GUESS_Y
          INITIAL_GUESS_Z-VAL
          INITIAL_GUESS_Z
          INITIAL_GUESS_ROLL-VAL
          INITIAL_GUESS_ROLL
          INITIAL_GUESS_PITCH-VAL
          INITIAL_GUESS_PITCH
          INITIAL_GUESS_YAW-VAL
          INITIAL_GUESS_YAW
          CLOUD_DESKEWED-VAL
          CLOUD_DESKEWED
          CLOUD_CORNER-VAL
          CLOUD_CORNER
          CLOUD_SURFACE-VAL
          CLOUD_SURFACE
          KEY_FRAME_CLOUD-VAL
          KEY_FRAME_CLOUD
          KEY_FRAME_COLOR-VAL
          KEY_FRAME_COLOR
          KEY_FRAME_POSES-VAL
          KEY_FRAME_POSES
          KEY_FRAME_MAP-VAL
          KEY_FRAME_MAP
))